const pessoasEmail = [{nome:"MARIA TEREZINHA DE SOUSA ARAUJO",email:"terezinhasousa.seducsobral@gmail.com"},
{nome:"ANTONIA PATRICIA LIMA",email:"antoniapatricialima123@gmail.com"},
{nome:"MALBA REGINA PEREIRA DA SILVA",email:"malba1978@hotmail.com"},
{nome:"ANDREA CARDOSO DOS SANTOS ROCHA",email:"andreacardoso1802seducsobral@gmail.com"},
{nome:"NATANA MARIA RODRIGUES DAMASCENO",email:"natanamrodrigues@gmail.com"},
{nome:"FERNANDA ARAGAO DE FRANÇA",email:"michelleelinhares@gmail.com"},
{nome:"MARIA ZENILDA BISPO",email:"zenilda_bispo57@hotmail.com "},
{nome:"ELIEUDA ALVES RODRIGUES",email:"elieuda.alves10@gmail.com"},
{nome:"FRANCISCA EDNA DE OLIVEIRA SILVA",email:"franciscaedna@edu.sobral.ce.gov.br"},
{nome:"AURICELIA SANTANA DE SOUSA",email:"auricelia@edu.sobral.ce.gov.br"},
{nome:"NONATA MARIA XAVIER",email:"nonatamariaxavier@gmail.com"},
{nome:"CRISTINA ANDRADE ALVES",email:"mil_grau1000@hotmail.com"},
{nome:"FRANCISCA GOMES MARQUES",email:"francisca.gomes.marques@edu.sobral.ce.gov.br"},
{nome:"LIDIANE AGUIAR RAMOS",email:"lidiane.aguiar@edu.sobral.ce.gov.br"},
{nome:"ZILMAR ALBUQUERQUE PARENTE",email:"zilmar.parente@edu.sobral.ce.gov.br"},
{nome:"DENISE ARAGÃO SOUSA",email:"denise.sousa@edu.sobral.ce.gov.br"},
{nome:"ANTONIA LEILA MACHADO PORTELA",email:"leila@edu.sobral.ce.gov.br"},
{nome:"MARIA DE LOURDES PARENTE",email:"maria.lourdes.parente@edu.sobral.ce.gov.br"},
{nome:"MARCELO ANGELO DE LIMA",email:"marcelo.angelo@edu.sobral.ce.gov.br"},
{nome:"ANTONIA DEUSILENE AGUIAR VAZ SOARES",email:"antonia.soares@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO DAS CHAGAS PAULINO SAMPAIO",email:"francisco.paulino@edu.sobral.ce.gov.br"},
{nome:"ANTONIA ELIZANGELA NERES LIMA",email:"elizangela@edu.sobral.ce.gov.br"},
{nome:"LILIANE XIMENES PONTE",email:"liliane.ximenes@edu.sobral.ce.gov.br"},
{nome:"JOSE OSMAR MONTEZUMA DE SOUZA",email:"osmar.souza@edu.sobral.ce.gov.br"},
{nome:"SIBERI LINHARES DA COSTA",email:"siberi@edu.sobral.ce.gov.br"},
{nome:"Francisca Alcenir Costa",email:"alcenir@edu.sobral.ce.gov.br"},
{nome:"YTAYARA RIBEIRO DE ALBUQUERQUE",email:"ytayara@edu.sobral.ce.gov.br"},
{nome:"JOSE GLEISON ALVES DA SILVA",email:"gleidson@edu.sobral.ce.gov.br"},
{nome:"VANESSA LIMA NERY OLIVEIRA",email:"vanessa.lima@edu.sobral.ce.gov.br"},
{nome:"ANDERSON ANDRE DE SOUZA",email:"anderson.andrade@edu.sobral.ce.gov.br"},
{nome:"JOSE HORLANDO SABINO DE SOUSA",email:"horlando@edu.sobral.ce.gov.br"},
{nome:"ELIANE EPIFANIO FERNANDES GOMES",email:"eliane@edu.sobral.ce.gov.br"},
{nome:"FLAVIA DE FATIMA MARQUES PEREIRA",email:"flavia@edu.sobral.ce.gov.br"},
{nome:"MARIA RUFINO CRUZ",email:"maria.rufino@edu.sobral.ce.gov.br"},
{nome:"MARIA DARLENE ARAUJO DO NASCIMENTO MOURA",email:"darlene.moura@edu.sobral.ce.gov.br"},
{nome:"NEIDE MARA SAMPAIO ",email:"neide.sampaio@edu.sobral.ce.gov.br"},
{nome:"MARCIA SOARES FERNANDES",email:"marcia@edu.sobral.ce.gov.br"},
{nome:"ANA CYZIA XIMENES DE MELO ARAGÃO",email:"cyzia@edu.sobral.ce.gov.br"},
{nome:"MARIA VALDENISA DUARTE DE OLIVEIRA",email:"valdenisa.duarte@edu.sobral.ce.gov.br"},
{nome:"MARIA LUCIMAR PINHEIRO GONÇALVES",email:"lucimar.goncalves@edu.sobral.ce.gov.br"},
{nome:"OSVALDO NETO DE SOUSA COSTA",email:"osvaldo@edu.sobral.ce.gov.br"},
{nome:"CARMEMSILVA BEZERRA GOMES",email:"carmem.silva@edu.sobral.ce.gov.br"},
{nome:"TEREZA MARIA MESQUITA SOUZA",email:"tereza@edu.sobral.ce.gov.br"},
{nome:"JOSE DILSON GOMES",email:"jose.gomes@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA ANA DOS SANTOS SOUSA",email:"francisca.ana.sousa@edu.sobral.ce.gov.br"},
{nome:"GLEIDSON MENDES MELO",email:"gleidson.melo@edu.sobral.ce.gov.br"},
{nome:"ARNOBIO BARBOZA ÁVILA",email:"arnobio.avila@edu.sobral.ce.gov.br"},
{nome:"RAFAELA MONTE DA SILVA",email:"rafaela.silva@edu.sobral.ce.gov.br"},
{nome:"ISAQUE ALMEIDA BEZERRA",email:"isaque@edu.sobral.ce.gov.br"},
{nome:"MACÁRIO CAETANO DE MENDONÇA FILHO",email:"macario.filho@edu.sobral.ce.gov.br"},
{nome:"ERINE MAGALHÃES RODRIGUES",email:"erine.rodrigues@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO ARISTIDES RODRIGUES DE PAIVA",email:"francisco.aristides@edu.sobral.ce.gov.br "},
{nome:"KELVIA MARIA DIAS JANUÁRIO",email:"kelvia@edu.sobral.ce.gov.br"},
{nome:"ANTONIA RODRIGUES MADEIRO",email:"antonia.madeiro@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO MOZART ALVES CARNEIRO",email:"francisco@edu.sobral.ce.gov.br "},
{nome:"LINNEKER FREIRE FROTA",email:"linneker@edu.sobral.ce.gov.br "},
{nome:"MARIA DA CONCEIÇÃO LAUREANO OLIVEIRA",email:"conceicao@edu.sobral.ce.gov.br "},
{nome:"JENIFFER PEREIRA ROCHA VALE",email:"jeniffer@edu.sobral.ce.gov.br "},
{nome:"REJANE MARIA DA PONTE VASCONCELOS",email:"rejane.ponte@edu.sobral.ce.gov.br "},
{nome:"JOSÉ ÍCARO CARVALHO FARIAS",email:"icaro.farias@edu.sobral.ce.gov.br"},
{nome:"HÉLIDA RODRIGUES DA SILVA",email:"helida@edu.sobral.ce.gov.br "},
{nome:"MARIA JAIRA XIMENES CARLOS",email:"jaira@edu.sobral.ce.gov.br "},
{nome:"VALÉRIA RIBEIRO MARQUES FERNANDES",email:"valeria@edu.sobral.ce.gov.br  "},
{nome:"PATRICIA MAGALHÃES FROTA",email:"patricia.magalhaes@edu.sobral.ce.gov.br "},
{nome:"CRISTIANO CAIXEIRO NASCIMENTO",email:"cristiano@edu.sobral.ce.gov.br "},
{nome:"ANTONIA CAROLINE RIBEIRO NOGUEIRA",email:"caroline@edu.sobral.ce.gov.br "},
{nome:"ANA PATRICIA MONÇÃO FIGUEREDO",email:"patricia.moncao@edu.sobral.ce.gov.br "},
{nome:"RAFAEL DANTAS DA SILVA",email:"rafael@edu.sobral.ce.gov.br "},
{nome:"SIMONE SILVA ALVES",email:"simonealvesbonfim@hotmail.com"},
{nome:"GESSICA FERNANDES SILVA",email:"gessica92-2011@hotmail.com"},
{nome:"MARIA CRIZEUDA SILVINO",email:"mariazilmasilvino@gmail.com"},
{nome:"ANDRELINE COELHO DA SILVA",email:"linesilva100@live.com"},
{nome:"JOELMA ALVES RODRIGUES",email:"joelma-alveslp@hotmail.com"},
{nome:"REBECA NIVEA ARAUJO",email:"rebecanivea01@gmail.com"},
{nome:"FRANCISCA APARECIDA BARBOSA",email:"franciscaaparecidabarbosab@gmail.com"},
{nome:"FRANCISCO HELOISO FERREIRA DE BRITO",email:"heloisobrito@yahoo.com.br"},
{nome:"MARIA GORETE VASCONCELOS",email:"m.govs@hotmail.com"},
{nome:"LEILIANE MACHADO PORTELA",email:"leiliane.machado@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO DAS CHAGAS FERREIRA CAVALCANTE",email:"francisco.ferreira@edu.sobral.ce.gov.br"},
{nome:"DANIELE DE BRITO RIBEIRO",email:"daniele.brito@edu.sobral.ce.gov.br"},
{nome:"AMANDA DA COSTA SOUSA AGUIAR",email:"amanda.aguiar@edu.sobral.ce.gov.br"},
{nome:"VALÉRIA LOPES RODRIGUES",email:"valeria.rodrigues@edu.sobral.ce.gov.br"},
{nome:"GEANE KELLY PEREIRA CORDEIRO",email:"geanekelly220489@gmail.com"},
{nome:"MARIA DO REMEDIO DE SOUSA ALVES",email:"maria.alves@edu.sobral.ce.gov.br"},
{nome:"JOÃO PAULO DA SILVA",email:"joaopaulomat999@gmail.com"},
{nome:"MARIA IARA BRITO E SILVA",email:"iaratudes15@gmail.com"},
{nome:"FRANCISCO GEOVANE DA SILVA ARAÚJO ",email:"geovane.silva@edu.sobral.ce.gov.br"},
{nome:"ANTONIA DAMASCENO ALVES PONTES ",email:"antoniapontes@edu.sobral.ce.gov.br"},
{nome:"ALUANA PONTE MENEZES",email:"aluana.menezes@edu.sobral.ce.gov.br"},
{nome:"FRANCILENE GONÇALVES ELIOTÉRIO ",email:"francilene.goncalves@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO LEANDRO LOURENÇO DO NASCIMENTO",email:"francisco.nascimento@edu.sobral.ce.gov.br"},
{nome:"MARIA ABIGAIL GONÇALVES ",email:"mariaabigailgoncalves02@gmail.com"},
{nome:"RAQUEL AUGUSTA DE MOURA ",email:"raquel.moura@edu.sobral.ce.gov.br"},
{nome:"MARIA TARCIANE MACHADO DE ALBUQUERQUE",email:"maria.albuqueruque@edu.sobral.ce.gov.br"},
{nome:"GLEIVIANE VITORINO FERREIRA ",email:"gleiviane.ferreira@edu.sobral.ce.gov.br"},
{nome:"SONIA MACHADO DA PONTE",email:"sonia.ponte@edu.sobral.ce.gov.br"},
{nome:"SANDRA RÉGIA DA SILVA ",email:"regia.silva@edu.sobral.ce.gov.br"},
{nome:"TADEU ALVES MEDEIROS ",email:"tadeu.medeiros@edu.sobral.ce.gov.br"},
{nome:"ATILA GOMES FERREIRA DA SILVA",email:"atila.silva@edu.sobral.ce.gov.br"},
{nome:"RAFAEL MANOEL DA PONTE VENUTO ",email:"rafael.venuto@edu.sobral.ce.gov.br"},
{nome:"FATIMA GEANE RIPARDO BATISTA",email:"fatima.batista@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO JOSÉ BERNARDINO DO NASCIMENTO",email:"bernardino@edu.sobral.ce.gov.br"},
{nome:"JOSÉ TAVARES DE OLIVEIRA FILHO",email:"jose.oliveira@edu.sobral.ce.gov.br"},
{nome:"JOELZA RODRIGUES FERREIRA",email:"joelza.ferreira@edu.sobral.ce.gov.br"},
{nome:"MARIA RENATA BORGES",email:"maria.borges@edu.sobral.ce.gov.br"},
{nome:"CLEMILDA DE LIMA ALBUQUERQUE",email:"clemilda.albuquerque@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO GALVAN SIMÃO DA SILVA",email:"galvanlegal@gmail.com"},
{nome:"ANA FLÁVIA SOUSA DE ARAÚJO",email:"ana.araujo@edu.sobral.ce.gov.br"},
{nome:"VANDERSON RODRIGUES NASCIMENTO",email:"vanderson.nascimento@edu.sobral.ce.gov.br"},
{nome:"DAIANNY RODRIGUES LOPES",email:"dayanny.lopes@edu.sobra.ce.gov.br"},
{nome:"FRANCISCA CARLANDIA LIMA DE SOUZA",email:"francisca.souza@edu.sobral.ce.gov.br"},
{nome:"GLAIZA CASSIMIRO PAIVA",email:"glaiza.paiva@edu.sobral.ce.gov.br"},
{nome:"MARCELA MELO RODRIGUES",email:"marcela.rodrigues@edu.sobral.ce.gov.br"},
{nome:"MICHELLE MARTINS VIANA",email:"michele.viana@edu.sobral.ce.gov.br"},
{nome:"ALEXANDRE DO NASCIMENTO ARAUJO",email:"alexandre.araujo@edu.sobral.ce.gov.br"},
{nome:"MARIA NAYARA BASTOS DE FREITAS SOUSA",email:"maria.freitas@edu.sobral.ce.gov.br"},
{nome:"EVANDRO BRITO DE ANDRADE",email:"evandro.andrade@edu.sobral.ce.gov.br"},
{nome:"GABRIEL MOTA FERREIRA",email:"gabriel.ferreira@edu.sobral.ce.gov.br"},
{nome:"LUIS FELIPE DE SOUSA BRANDAO",email:"luis.brandao@edu.sobral.ce.gov.br"},
{nome:"MARIA GLEICIA PAIVA LUCAS",email:"maria.lucas@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO ARTUR COSTA BASTOS",email:"francisco.barros@edu.sobral.ce.gov.br"},
{nome:"AUFRAN JUNIOR ALBUQUERQUE TELES",email:"aufran.teles@edu.sobral.ce.gov.br"},
{nome:"BENEDITA NIELE RODRIGUES LIMA",email:"benedita.lima@edu.sobral.ce.gov.br"},
{nome:"DANIEL ROSENDO DE OLIVEIRA",email:"daniel.oliveira@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO ANTUNES RODRIGUES DOS SANTOS",email:"francisco.santos@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO REGIS CORDEIRO DA SILVA",email:"regis.silva@edu.sobral.ce.gov.br"},
{nome:"FRANCO MARCELINO OLIVEIRA",email:"franco.oliveira@edu.sobral.ce.gov.br"},
{nome:"JOSE GOMES BRAGA",email:"jose.braga@edu.sobral.ce.gov.br"},
{nome:"JOSE WELLINGTON RODRIGUES DE LIMA",email:"wellington.lima@edu.sobral.ce.gov.br"},
{nome:"MARCIA PONTES DIAS ALVES",email:"marcia.alves@edu.sobral.ce.gov.br"},
{nome:"MARCIANO VASCONCELOS FERREIRA",email:"marciano.ferreira@edu.sobral.ce.gov.br"},
{nome:"MARIA MAILANE VIEIRA DA SILVA",email:"maria.mailane@edu.sobral.ce.gov.br"},
{nome:"MARIA NAIANE MOITA",email:"maria.moita@edu.sobral.ce.gov.br"},
{nome:"PAULO CEZAR VASCONCELOS",email:"paulo.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"PAULO RICARDO MESQUITA MOREIRA",email:"paulo.moreira@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDO CLEHILTON MARQUES SOUSA",email:"clehilton@edu.sobral.ce.gov.br"},
{nome:"REGIANE RIPARDO MAIA",email:"regiane.maia@edu.sobral.ce.gov.br"},
{nome:"SIMONE LIMA SALES",email:"simone.lima@edu.sobral.ce.gov.br"},
{nome:"MARIA ADRIANA DOS SANTOS CARNEIRO",email:"adriana.carneiro@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA CARNEIRO DOS SANTOS",email:"francisca.carneiro@edu.sobral.ce.gov.br"},
{nome:"CLECIO EMANUEL MARTINS FREITAS",email:"clecio.freitas@edu.sobral.ce.gov.br"},
{nome:"EMANUELA TORRES VASCONCELOS",email:"emanuela.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"EDMAR MIRANDA AVILA JUNIOR",email:"edmar.avila.junior@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO BRITO AZEVEDO",email:"francisco.brito@edu.sobral.ce.gov.br"},
{nome:"JAQUELINE DE SOUSA FERREIRA",email:"jaqueline.ferreira@edu.sobral.ce.gov.br"},
{nome:"BENEDITA BEZERRA FROTA",email:"benedita.frota@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO IVAN FERREIRA DE SOUSA",email:"ivan.ferreira@edu.sobral.ce.gov.br"},
{nome:"IVANESSA COELHO RODRIGUES",email:"ivanessa.rodrigues@edu.sobral.ce.gov.br"},
{nome:"JAQUELINE COSTA SOARES DA ROCHA",email:"jaqueline.rocha@edu.sobral.ce.gov.br"},
{nome:"JOSE ADALBERTO FERREIRA ARAUJO",email:"jose.araujo@edu.sobral.ce.gov.br"},
{nome:"LEANDRO PORTELA DE LIMA",email:"leandro.lima@edu.sobral.ce.gov.br"},
{nome:"LUCIANO EPIFANIO FERNANDES",email:"luciano.fernandes@edu.sobral.ce.gov.br"},
{nome:"MAGNUN PORTELA PEREIRA",email:"magnun.portela@edu.sobral.ce.gov.br"},
{nome:"MARIA DAS GRACAS LIMA",email:"maria.das.gracas@edu.sobral.ce.gov.br"},
{nome:"VALDERLANE GOMES DE ALBUQUERQUE VAZ CORDEIRO",email:"valderlane.cordeiro@edu.sobral.ce.gov.br"},
{nome:"ANTONIA MARIA FÉLIX",email:"antoniamariafelix@hotmail.com "},
{nome:"FRANSQUINHA VASCONCELOS DOS SANTOS",email:"kaquinhainfantil@gmail.com "},
{nome:"MARIA IRISMAR SOUSA",email:"irismar_sousa@live.com "},
{nome:"VICENTE DE PAULO ARAÚJO DE MATOS",email:"vicentedepaulo77@yahoo.com.br "},
{nome:"ADRIANA MADEIRA DE LIMA",email:"adrianamadeiradrik@hotmail.com "},
{nome:"LUCIANO XAVIER RIBEIRO",email:"lucianoxavierribeiroxavier@gmail.com"},
{nome:"CLARICE LOPES DE SOUSA",email:"clariceliardo@hotmail.com "},
{nome:"CARLOS HENRIQUE PEREIRA LINS",email:"henriquelins84@yahoo.com "},
{nome:"FRANCISCA CELIA CORDEIRO ARAUJO CEZARIO",email:"franciscacelia@edu.sobralce.gov.br."},
{nome:"YARA RENATA DIAS DE LOIOLA",email:"codinomebeijaflor27@hotmail.com"},
{nome:"CLEIDINI PAIVA LOPES",email:"cleidinipaivalopes@hotmail.com"},
{nome:"AGUIDA MARIA ARAUJO",email:"aguidaaraujo2009@hotmail.com"},
{nome:"MARIA AURECILIA AVILA PINTO",email:"aurecilia2019@gmail.com"},
{nome:"MARIA LUCIENE SIQUEIRA",email:"maria.siqueira@edu.sobral.ce.gov.br"},
{nome:"SILVIA HELENA MENDES HONORIO MESQUITA",email:"silvinha.hm@hotmail.com"},
{nome:"ASENATE MOURA ALMEIDA",email:"asenate78@gmail.com"},
{nome:"VANUZA AVILA ROCHA",email:"vanuza_avila@hotmail.com"},
{nome:"FRANCISCA DANIELE VIANA PONTE MESQUITA",email:"danielemesquita28@hotmail.com"},
{nome:"VALDIANA LOPES DE AVILA",email:"valdianavila@hotmail.com"},
{nome:"JOSE AUDANIO AVILA PINTO",email:"audanioavila@gmail.com"},
{nome:"ROBERVANDA ALVES PINTO",email:"alvesrobervanda@gmail.com"},
{nome:"FRANCISCO AIRTON MENDES",email:"airton137@hotmail.com"},
{nome:"ISAQUE ALMEIDA BEZERRA",email:"isaquealmeidabezerra@gmail.com"},
{nome:"FRANCISCO ANTONIO TEOFILO ANDRE",email:"francisco.andre@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO ARISTIDES PINTO MENDES",email:"aristidesmendes.seducsobral@gmail.com"},
{nome:"THAIS LACERDA DE AZEVEDO",email:"thais@edu.sobral.ce.gov.br"},
{nome:"THAIS LACERDA DE AZEVEDO",email:"thais@edu.sobral.ce.gov.br"},
{nome:"DANIELA MARIA DE SOUSA AGUIAR",email:"daniela@edu.sobral.ce.gov.br  "},
{nome:"DANIELA MARIA DE SOUSA AGUIAR",email:"daniela@edu.sobral.ce.gov.br  "},
{nome:"OSMILDO PORTELA PONTES",email:"osmildo@edu.sobral.ce.gov.br  "},
{nome:"ANDRESSA KELLE DE SOUSA",email:"andressa.kelle@edu.sobral.ce.gov.br"},
{nome:"ANGELA CARLA SILVA DA COSTA",email:"angela@edu.sobral.ce.gov.br"},
{nome:"ANTONIA FLAVIA DE SOUSA SILVA",email:"flavia.silva@edu.sobral.ce.gov.br"},
{nome:"ANTONIA LUCEMA MENDES PAIVA",email:"lucema.paiva@edu.sobral.ce.gov.br"},
{nome:"ANTONIA ROSIANA BARBOSA",email:"rosiana.barbosa@edu.sobral.ce.gov.br"},
{nome:"CARMODILHA LIMA DE SOUSA",email:"carmodilha.sousa@edu.sobral.ce.gov.br"},
{nome:"CINTHIA PAIXAO DOS SANTOS",email:"cinthia.santos@edu.sobral.ce.gov.br"},
{nome:"CLAUDIANA BRITO DE PAIVA",email:"claudiana.paiva@edu.sobral.ce.gov.br"},
{nome:"CLEANE SILVA MELO",email:"cleane.melo@edu.sobral.ce.gov.br"},
{nome:"CONCEIÇÃO DE MARIA CRUZ RODRIGUES",email:"conceicao.rodrigues@edu.sobral.ce.gov.br"},
{nome:"ELIDA JANE PORFIRIO FARIAS",email:"elida.farias@edu.sobral.ce.gov.br"},
{nome:"ELOA SALGADO DE CARVALHO BARBOSA",email:"eloa.barbosa@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA DAS CHAGAS DE OLIVEIRA MESQUITA",email:"francisca.chagas.oliveira@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO WELLINGTON HIGINO SOUSA",email:"wellington.sousa@edu.sobral.ce.gov.br"},
{nome:"IRENE MATOS DE SOUSA",email:"irene.matos@edu.sobral.ce.gov.br"},
{nome:"IVAN LENNON DA COSTA NOGUEIRA",email:"ivan.nogueira@edu.sobral.ce.gov.br"},
{nome:"LEONARDO FERREIRA SAMPAIO",email:"leonardo.sampaio@edu.sobral.ce.gov.br"},
{nome:"LUCIANA SOARES DA COSTA",email:"luciana.costa@edu.sobral.ce.gov.br"},
{nome:"MARIA AURENI DE PAULO ANDRADE",email:"aureni.andrade@edu.sobral.ce.gov.br"},
{nome:"MARIA AURILEIDE DOS SANTOS",email:"aurileide.santos@edu.sobral.ce.gov.br"},
{nome:"MARIA AURIMAR GUIMARAES XIMENES",email:"aurimar.ximenes@edu.sobral.ce.gov.br"},
{nome:"MARIA DO SOCORRO CARNEIRO FARIAS",email:"socorro.carneiro@edu.sobral.ce.gov.br"},
{nome:"MARIA DO SOCORRO SALES RIBEIRO GALVAO",email:"maria.galvao@edu.sobral.ce.gov.br"},
{nome:"MARIA ONETE RIBEIRO CALDERARO DA SILVA",email:"onete.silva@edu.sobral.ce.gov.br"},
{nome:"PAULO RICARDO RODRIGUES PRADO",email:"paulo.prado@edu.sobral.ce.gov.br"},
{nome:"RITA DE CASSIA ARAUJO",email:"rita.araujo@edu.sobral.ce.gov.br"},
{nome:"SAMIA MARIA MENEZES PONTE",email:"samia.ponte@edu.sobral.ce.gov.br"},
{nome:"SHIRLEY SANDRA DE SOUSA ARAUJO",email:"shirley.sousa@edu.sobral.ce.gov.br"},
{nome:"SILVANA MARIA DA SILVA CHAGAS",email:"silvana.chagas@edu.sobral.ce.gov.br"},
{nome:"SOLANGE MARIA FREIRE DA SILVA RODRIGUES",email:"solange.rodrigues@edu.sobral.ce.gov.br"},
{nome:"TERESINHA DE ARAGAO GOMES",email:"teresinha.gomes@edu.sobral.ce.gov.br"},
{nome:"TERESINHA DE JESUS PARENTE LINHARES",email:"teresinha.linhares@edu.sobral.ce.gov.br"},
{nome:"ALEXANDRA MARIA SILVA DE CASTRO ",email:"alexandra.maria@edu.sobral.ce.gov.br"},
{nome:"ANA ALICE FERREIRA DE PAULA",email:"ana.alice@edu.sobral.ce.gov.br"},
{nome:"ANA KARLA VASCONCELOS",email:"ana.karla@edu.sobral.ce.gov.br"},
{nome:"ANA KÉLVIA DE LIRA RIBEIRO",email:"ana.kelvia@edu.sobral.ce.gov.br"},
{nome:"ANA MIKAELLY MADEIRA ALBUQUERQUE",email:"ana.mikaelly@edu.sobral.ce.gov.br"},
{nome:"ANA PAULA LINHARES",email:"ana.paula@edu.sobral.ce.gov.br"},
{nome:"CARLA THIARA DE ARAÚJO SOUSA",email:"carla.thiara@edu.sobral.ce.gov.br"},
{nome:"CIDÁLIA BEZERRA DOS SANTOS NETO",email:"cidalia.bezerra@edu.sobral.ce.gov.br"},
{nome:"CLEINILDA ALVES MEDEIROS FERREIRA",email:"cleinilda.alves@edu.sobral.ce.gov.br"},
{nome:"ERIKA MESQUITA DE SALES",email:"erika.mesquita@edu.sobral.ce.gov.br"},
{nome:"FRANCINILDA RODRIGUES ANDRADE VASCONCELOS",email:"francinilda.rodrigues@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA DAS CHAGAS DE OLIVEIRA MESQUITA",email:"francisca.chagas.oliveira@edu.sobral.ce.gov.br"},
{nome:"Francisca das Chagas Linhares Ribeiro de Menezes",email:"francisca.menezes@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO JANIO RODRIGUES",email:"francisco.janio@edu.sobral.ce.gov.br"},
{nome:"GESSIANE LIBERATO MOURA",email:"gessiane.liberato@edu.sobral.ce.gov.br"},
{nome:"GILDETE ANDRADE ALCANTARAS",email:"gildete.andrade@edu.sobral.ce.gov.br"},
{nome:"GILVANA MESQUITA CAETANO",email:"gilvana.mesquita@edu.sobral.ce.gov.br"},
{nome:"GRACE KELL DE ARAÚJO CARNEIRO",email:"grace.kell@edu.sobral.ce.gov.br"},
{nome:"IVANA MARIA MORAIS MELO",email:"ivana.maria@edu.sobral.ce.gov.br"},
{nome:"JOÃO BATISTA LIMA ARAGÃO",email:"joao.batista@edu.sobral.ce.gov.br"},
{nome:"JOELMA GOMES FERREIRA",email:"joelma.gomes@edu.sobral.ce.gov.br"},
{nome:"JOSÉ RIBAMAR GOMES",email:"jose.ribamar@edu.sobral.ce.gov.br"},
{nome:"JOSÉ RONIER RODRIGUES DA SILVA",email:"jose.ronier@edu.sobral.ce.gov.br"},
{nome:"KATIA CILENE COSTA OLIVEIRA DA SILVA",email:"katia.cilene@edu.sobral.ce.gov.br"},
{nome:"KEICIANE ALMEIDA SOUSA",email:"keiciane.almeida@edu.sobral.ce.gov.br"},
{nome:"LUCILENE MATIAS RIPARDO",email:"lucilene.matias@edu.sobral.ce.gov.br"},
{nome:"LUZINEIDE MONTE FRANÇA",email:"luzineide.monte@edu.sobral.ce.gov.br"},
{nome:"MANUELA CARLA DO NASCIMENTO SOUZA DOS SANTOS ",email:"manuela.carla@edu.sobral.ce.gov.br"},
{nome:"MARA RÉGIA SILVA DA COSTA",email:"mara.regia@edu.sobral.ce.gov.br"},
{nome:"MARCIA JACKELINE DE SOUSA OLIVEIRA",email:"marcia.jackeline@edu.sobral.ce.gov.br"},
{nome:"MÁRCIA MARIA GONÇALVES DE MESQUITA",email:"marcia.maria@edu.sobral.ce.gov.br"},
{nome:"MARIA ANGELUCIA DE SOUSA ALBUQUERQUE",email:"maria.angelucia@edu.sobral.ce.gov.br"},
{nome:"MARIA CELMER RONCY",email:"maria.celmer@edu.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEIÇAO GOMES MENDES",email:"maria.da@edu.sobral.ce.gov.br"},
{nome:"MARIA DO CARMO SILVA DE MESQUITA",email:"maria.do@edu.sobral.ce.gov.br"},
{nome:"MARIA ELIENE PORTO RODRIGUES ",email:"maria.eliene@edu.sobral.ce.gov.br"},
{nome:"MARIA ELISANGELA DE SOUSA PAZ",email:"maria.elisangela@edu.sobral.ce.gov.br"},
{nome:"MARIA ESTELA AMBRÓSIO FÉLIX",email:"maria.estela@edu.sobral.ce.gov.br"},
{nome:"MARIA IVANI SOUZA",email:"maria.ivani@edu.sobral.ce.gov.br"},
{nome:"MARIA JEÍZA PEREIRA DE MATOS",email:"maria.jeiza@edu.sobral.ce.gov.br"},
{nome:"MARIA JOYCE DE ARAÚJO SÁ",email:"maria.joyce@edu.sobral.ce.gov.br"},
{nome:"MARIA LIDIANE DE SOUSA MELO",email:"maria.lidiane@edu.sobral.ce.gov.br"},
{nome:"MARIA LIGIA LOPES LAURINDO",email:"maria.ligia@edu.sobral.ce.gov.br"},
{nome:"MARIA OZENICE OLIVEIRA",email:"maria.ozenice@edu.sobral.ce.gov.br"},
{nome:"MARIA SIMONE DE FARIAS HILÁRIO",email:"maria.simone@edu.sobral.ce.gov.br"},
{nome:"MIQUEAS ROMAO GADELHA",email:"miqueas.romao@edu.sobral.ce.gov.br"},
{nome:"NAIZA MARIA SILVA OLIVEIRA",email:"naiza.maria@edu.sobral.ce.gov.br"},
{nome:"PATRICIA NASCIMENTO AGUIAR",email:"patricia.nascimento@edu.sobral.ce.gov.br"},
{nome:"RAPHAEL CATUNDA BASTOS",email:"raphael.catunda@edu.sobral.ce.gov.br"},
{nome:"REGINA MARIA DE LOIOLA",email:"regina.maria@edu.sobral.ce.gov.br"},
{nome:"ROGERIO MATOS MAGALHAES",email:"rogerio.matos@edu.sobral.ce.gov.br"},
{nome:"ROSA MARIA TORRES SEGUNDO",email:"rosa.torres@edu.sobral.ce.gov.br"},
{nome:"ROSÂNGELA SILVA DA COSTA",email:"rosangela.silva@edu.sobral.ce.gov.br"},
{nome:"SIMONE MARQUES ROCHA",email:"simone.marques@edu.sobral.ce.gov.br"},
{nome:"THAYANA DE SOUZA BARROSO",email:"simone.marques@edu.sobral.ce.gov.br"},
{nome:"ANTONIA BETIJANE BATISTA RODRIGUES",email:"antonia.betijane@edu.sobral.ce.gov.br"},
{nome:"ANTONIA EUCLIA MOREIRA SALES",email:"antonia.euclia@edu.sobral.ce.gov.br"},
{nome:"ANTONIA FLAVIA PARENTE DA PONTE",email:"antonia.flavia@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO WELTON GOMES DAMASCENO",email:"francisco.welton@edu.sobral.ce.gov.br"},
{nome:"JAQUELINE ÁVILA MESQUITA",email:"jaqueline.avila@edu.sobral.ce.gov.br"},
{nome:"VANESSA MONICA ARAÚJO SABÓIA",email:"vanessa.monica@edu.sobral.ce.gov.br"},
{nome:"ANA LÚCIA LEITE VASCONCELOS",email:"ana.lucia@edu.sobral.ce.gov.br"},
{nome:"ANTONIA XIMENES PONTE",email:"antonia.ximenes@edu.sobral.ce.gov.br"},
{nome:"CARLA CRISTINA LIRA LIMA ARCANJO",email:"carla.cristina@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA EDILENE MATIAS DA SILVA ",email:"edilene.silva@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA ÉLBIA PAULO BORGES",email:"elbia_borges@hotmail.com"},
{nome:"MARIA LIDUNA SOUSA",email:"maria.liduina@edu.sobral.ce.gov.br"},
{nome:"ROSA MARIA VIEIRA ROQUE",email:"rosa.roque@edu.sobral.ce.gov.br"},
{nome:"ALINE DAIANE SOARES SILVA COSTA",email:"aline.daiane@edu.sobral.ce.gov.br"},
{nome:"AMANDA CRISTINA VIEIRA DA COSTA",email:"amanda.cristina@edu.sobral.ce.gov.br"},
{nome:"ANA CRISTINA SOUSA FILOMENO",email:"ana.cristina@edu.sobral.ce.gov.br"},
{nome:"ANA RAQUEL DOS SANTOS SOUSA",email:"ana.raquel@edu.sobral.ce.gov.br"},
{nome:"ANTONIA DE SOUSA LIRA DOMINGUES",email:"antonia.de@edu.sobral.ce.gov.br"},
{nome:"CINDY ADRINY SANTOS ALEXANDRE",email:"cindy.adriny@edu.sobral.ce.gov.br"},
{nome:"FLORENCIA IVA QUEIROZ DE SOUSA",email:"florencia.iva@edu.sobral.ce.gov.br"},
{nome:"LUCAS DE SOUSA FERREIRA",email:"lucas.de@edu.sobral.ce.gov.br"},
{nome:"LUZIA DE CARVALHO ROCHA",email:"luzia.de@edu.sobral.ce.gov.br"},
{nome:"MARIA JESSICA SALES MIRANDA",email:"maria.jessica@edu.sobral.ce.gov.br"},
{nome:"MARIA LETICIA SOUSA MOURA DE MORAIS",email:"maria.leticia@edu.sobral.ce.gov.br"},
{nome:"MARIA WISLLA COSTA DUARTE",email:"maria.wislla@edu.sobral.ce.gov.br"},
{nome:"RAIANA MARIA MOTA DIAS",email:"raiana.maria@edu.sobral.ce.gov.br"},
{nome:"SAMANTHA ALVES ZUZA CARVALHO",email:"samantha.alves@edu.sobral.ce.gov.br"},
{nome:"SANDRA MARIA SILVA BORGES",email:"sandra.maria@edu.sobral.ce.gov.br"},
{nome:"TANIA MARIA FERNANDES RODRIGUES",email:"tania.maria@edu.sobral.ce.gov.br"},
{nome:"VALNICE DE SOUSA LIRA",email:"valnice.sousa@edu.sobral.ce.gov.br"},
{nome:"MARIA ELENICE RODRIGUES FEIJÃO               ",email:"maria.elenice@educ.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEIÇÃO GOMES CARNEIRO",email:"conceicao.gomes@edu.sobral.ce.gov.br"},
{nome:"MARIA VALDEVANDA SANTANA GOMES",email:"valdevanda@edu.sobral.ce.gov.br"},
{nome:"ALEXANDRINA VASCONCELOS GOMES",email:"alexandrina@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA EMANUELA RIBEIRO DE SOUSA",email:"francisca.emanuela@edu.sobral.ce.gov.br"},
{nome:"MARIA AUGUSTA DA SILVA GOMES",email:"augusta.gomes@edu.sobral.ce.gov.br"},
{nome:"MARIA OTÍLIA MONTEIRO GOMES",email:"otilia@edu.sobral.ce.gov.br"},
{nome:"MARIA AUGUSTA DA SILVA GOMES",email:"augusta.gomes@edu.sobral.ce.gov.br"},
{nome:"JOSÉ HERMENEGILDO MESQUITA VIANA",email:"jose.viana@edu.sobral.ce.gov.br"},
{nome:"MARINA DA SILVA DE CARVALHO",email:"marina.carvalho@edu.sobral.ce.gov.br"},
{nome:"RUTHIELLE MARTINS PRADO",email:"ruthielle.prado@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO SILVIO PEREIRA DUARTE",email:"francisco.pereira@edu.sobral.ce.gov.br"},
{nome:"GLEICE KELLY FROTA DE CASTRO",email:" gleicecastro@edu.sobral.ce.gov.br"},
{nome:"MARIA VANI GOMES",email:"mariagomes@edu.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEIÇÃO ALCANTARA",email:"mariaalcantara@edu.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEIÇÃO GOMES ALVES",email:"mariaalves@edu.sobral.ce.gov.br"},
{nome:"MARIANA ALBANHA DOS SANTOS BRATZ",email:"marianabratz@edu.sobral.ce.gov.br"},
{nome:"MARIA ELAINE ARAUJO DAMASCENO",email:"mariadamasceno@edu.sobral.ce.gov.br"},
{nome:"CELINA EDUARDO SOUZA",email:"celinasouza@edu.sobral.ce.gov.br"},
{nome:"REJANE MARIA SILVA LIMA",email:"rejane-msl@hotmail.com"},
{nome:"MARIA AUXILIADORA XIMENES DE SOUSA",email:"dodorasobral@hotmail.com"},
{nome:"AURINELIA DE SOUSA SILVA",email:"aurineliasousasilva@yahoo.com"},
{nome:"DIANA MARA DE SOUZA MATOS",email:"dianamara05de@gmail.com"},
{nome:"MOUSIELY SAMYA SOARES MOREIRA",email:"mousiely@hotmail.com "},
{nome:"RENI MARIA SILVA ",email:"renimaria.iza@gmail.com"},
{nome:"ANTONIO MARCOS DO NASCIMENTO ",email:"joeliamarcos10@hotmail.com"},
{nome:"IRISBEL LIMA DE ALCANTARA ",email:"iris.alcantara@hotmail.com"},
{nome:"MARIA JACIARA RODRIGUES MELO FEIJAO",email:"jaciaramelof2@outlook.com"},
{nome:"Ana Carla de Mesquita",email:"anacarlasobral76@gmail.com"},
{nome:"Andreia Gomes Santana",email:"andreia.santana@edu.sobral.ce.gov.br"},
{nome:"Apolônia Machado Mesquita",email:"apolonia.mesquita@edu.sobral.ce.gov.br"},
{nome:"Clecia Teixeira de Paiva",email:"clecia.paiva@edu.sobral.ce.gov.br"},
{nome:"Edna Maria de Sousa",email:"edna.sousa@edu.sobral.ce.gov.br"},
{nome:"Erithusia Ximenes Lopes",email:"erithusia.lopes@edu.sobral.ce.gov.br"},
{nome:"Fabiana Sousa Fernandes",email:"fabiana.fernandes@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA ERIKA DA SILVA SOUSA",email:"erika.sousa@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA FABIANA ALVES OLIVEIRA",email:"francisca.fabiana@edu.sobral.ce.gov.br"},
{nome:"Francisca Francilene de Oliveira Carlos",email:"francisca.carlos@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA GELIANA DE ALBUQUERQUE",email:"geliana@edu.sobral.ce.gov.br"},
{nome:"Jamile Venâncio de Oliveira",email:"jamile.oliveira@edu.sobral.ce.gov.br"},
{nome:"Jones Relson Duarte Bento",email:"jones.bento@edu.sobral.ce.gov.br"},
{nome:"Joreolana Brito da Silva",email:"joreolana.silva@edu.sobral.ce.gov.br"},
{nome:"Maria Diva Neves Mendes Carneiro",email:"diva.carneiro@edu.sobral.ce.gov.br"},
{nome:"Maria do Socorro Mesquita Sousa",email:"socorro.mesquita@edu.sobral.ce.gov.br"},
{nome:"Maria do Socorro Parente Vasconcelos",email:"socorroparente5@gmail.com"},
{nome:"Maria do Socorro Sousa Silva",email:"socorro.silva@edu.sobral.ce.gov.br"},
{nome:"Maria Suely Sales Ferreira",email:"suely.ferreira@edu.sobral.ce.gov.br"},
{nome:"Neomesia Monteiro Lopes",email:"neomesia.lopes@edu.sobral.ce.gov.br"},
{nome:"Oziel Valerio Rodrigues",email:"oziel.rodrigues@edu.sobral.ce.gov.br"},
{nome:"Regina Telma Dias Ferreira",email:"telmaedclara@gmail.com"},
{nome:"Rosimeire de Lima Melo",email:"rosimeire.melo@edu.sobral.ce.gov.br"},
{nome:"Tiane Linhares da Silva",email:"tiane.silva@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA GUILHERMINA BRASILEIRO MAGALHÃES",email:"francisca.guilhermina@edu.sobral.ce.gov.br"},
{nome:"MARIA ELIANE ALVES PEREIRA",email:"maria_69_alves@outlook.com"},
{nome:"APARECIDA CASSIMIRO DE LIMA",email:"aparecidacassimiro@hotmail.com"},
{nome:"ANA CRISTINA RIBEIRO MENEZES ",email:"ana.menezes@edu.sobral.ce.gov.br"},
{nome:"EMANUELLE COSTA RIPARDO",email:"leolavinialara@gmail.com"},
{nome:"ENILBA PARENTE DE MENEZES",email:"enilba.menezes@edu.sobral.ce.gov.br"},
{nome:"MARIA DE FATIMA DE OLIVEIRA PONTE",email:"fafaoliveira059@gmail.com"},
{nome:"FRANCISCO EDMILSON SILVA ",email:"edimilson.silva@edu.sobral.ce.gov.br"},
{nome:"SANDRA REGIA DE SOUSA",email:"ardnasaiger@gmail.com"},
{nome:"MARIA DE JESUS AGUIAR",email:"dejesusaguiarmaria@gmail.com"},
{nome:"ANA JAMILLE AGUIAR PARENTE",email:"jamilleagiar002@gmail.com"},
{nome:"SANDRA REGIA DE SOUSA",email:"ardnasaiger@gmail.com"},
{nome:"MARIA DE JESUS  AGUIAR",email:"dejesusaguiarmaria@gmail.com"},
{nome:"MARIA DO SOCORRO ANDRADE LIMA",email:"maria.andrade@edu.sobral.ce.gov.br"},
{nome:"EVANIA MACHADO DO CARMO ADRIANO",email:"evania.machado@hotmail.com"},
{nome:"IVANIA MACHADO XIMENES",email:"ivaniamachado24@hotmail.com"},
{nome:"CRISTIANE MARIA VASCONCELOS LINHARES",email:"crisvl7@hotmail.com"},
{nome:"IVANIA MACHADO XIMENES",email:"ivaniamachado24@hotmail.com"},
{nome:"EDNA MARIA FERREIRA GOMES",email:"ednamaria2001@hotmail.com"},
{nome:"CONCEIÇÃO DE MARIA COSTA DE PAULA CLEMENTE",email:"conceicaorp@hotmail.com"},
{nome:"FRANCISCA HIARA PEREIRA DE SOUSA",email:"hiarasousa09@hotmail.com"},
{nome:"VALESKA SIRIDÓ LIMA",email:"leskalima@hotmail.com"},
{nome:"MARCOS ANTONIO DE OLIVEIRA FILHO",email:"tonnyohlif@hotmail.com"},
{nome:"KATIDIANE VASCONCELOS BEZERRA ROCHA",email:"kvbrocha3@gmail.com"},
{nome:"JOSIEL MOTA PEREIRA",email:"josielmp3seducsobral@gmail.com"},
{nome:"RENATO ANTONIO COSTA",email:"renatoantoniocosta@hotmail.com"},
{nome:"FRANCISCO KLEBER RODRIGUES ALVES",email:"kleber.forquilha38@gmail.com"},
{nome:"FRANCISCA ISAQUIELY XIMENES ARAUJO",email:"isaquielyximenesaraujo@gmail.com"},
{nome:"MIKAELE CORREIA DA SILVA MOURA",email:"mikaele.c.silva@gmail.com"},
{nome:"NILTON DO VALE CAVALCANTE",email:"valedonilton@gmail.com"},
{nome:"MARIA DAIANE DUARTE DE VASCONCELOS",email:"daianevasconcelos01@gmail.com"},
{nome:"MARIA AUXILIADORA CARNEIRO AUZIER",email:"mariaauxiliadora.seducsobral@gmail.com"},
{nome:"GILBERTO MACIEL PAIVA JUNIOR",email:"juninbebe@hotmail.com"},
{nome:"JOÃO FERREIRA DOMINGOS FILHO",email:"joaoemessanger@hotmail.com"},
{nome:"ADRIANA DE OLIVEIRA",email:"adrianamorena5555@gmail.com"},
{nome:"ANA CAROLINA CELESTINO",email:"karolina.cavalcante05@gmail.com"},
{nome:"ANA TAFNES DE SOUSA RODRIGUES",email:"anatafnes.tr@gmail.com"},
{nome:"ANDREA MONTE DA SILVA",email:"andy_deia30@hotmail.com"},
{nome:"ANDRÉ JOAQUIM DE ARAÚJO",email:"andre.araquim@hotmail.com"},
{nome:"ANTONIO MARIO ALVES DO NASCIMENTO",email:"marioalves0205@gmail.com"},
{nome:"DOUGLAS ABREU BRAGA DE SOUZA",email:"keitaro2006@hotmail.com"},
{nome:"ERTON FREIRE LAUREANO",email:"ertonprofmat@hotmail.com"},
{nome:"FRANCISCA JOELIA NEVES",email:"francisca.neves@edu.sobral.ce.gov.br"},
{nome:"JOSIER RIPARDO NASCIMENTO",email:"nascimento12ripardo@gmail.com"},
{nome:"LILIANE MARIA MACEDO FERREIRA",email:"anne_enailil@hotmail.com"},
{nome:"MARIA ISABEL DO MONTE LOPES",email:"isabel_19lopes@hotmail.com"},
{nome:"MARIA JOSIANE MOREIRA DE SAMPAIO",email:"josy_moraujo@hotmail.com"},
{nome:"NAYARA SILVA DE OLIVEIRA",email:"oliveiranayara965@gmail.com"},
{nome:"RAIMUNDO NONATO MONTEIRO",email:"raimundononatomonteiro7@gmail.com"},
{nome:"ROMERIO FREIRE ALCANTARA",email:"romerio.freire@hotmail.com"},
{nome:"TELMA MENDES PINTO",email:"telmamendesp@hotmail.com"},
{nome:"MILENA ÁVILA GONÇALVES",email:"miliena_avilag@hotmail.com"},
{nome:"GESSICA MAGALHAES RIBEIRO",email:"gessicamagalhaes@hotmail.com"},
{nome:"ROBERVANDA ALVES PINTO",email:"alvesrobervanda@gmail.com"},
{nome:"ANA CLAUDIA MOURA ALMEIDA",email:"amouralmeida@hotmail.com"},
{nome:"ANA CLAUDIA MOURA ALMEIDA",email:"amouralmeida@hotmail.com"},
{nome:"FRANCISCO AIRTON MENDES",email:"airton137@hotmail.com"},
{nome:"JOSE WILSON RODRIGUES PINTO",email:"wilsinhrodrigues10@gmail.com"},
{nome:"URCULA MARIA ALMEIDA MENDES",email:"urculamendesgmail.com"},
{nome:"FRANCISCA JULIA AVELINO MARREIRO",email:" franciscajulia@edu.sobral.ce.gov.br"},
{nome:"AMANDA BEZERRA LOPES",email:"amanda@edu.sobral.ce.gov.br"},
{nome:"ANA FLAVIA VERDE SAMPAIO VASCONCELOS",email:"anaflavia@edu.sobral.ce.gov.br"},
{nome:"ANTONIO FERNANDES TOMAZ FILHO",email:"antoniofernandes@edu.sobral.ce.gov.br"},
{nome:"CLECIVANE OLIVEIRA ALBUQUERQUE",email:"klecivany@hotmail.com "},
{nome:"DAVILA DE MESQUITA SOUSA",email:"davila@edu.sobral.ce.gov.br"},
{nome:"FERNANDA KARLA FELISMINO PIMENTEL",email:"fernandakarla@edu.sobral.ce.gov.br"},
{nome:"Francisca Lúcia Marques de Aragão",email:"francisca.aragao@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA LUSIELMA LINHARES",email:"francisca.linhares@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA LUZINETE DE ALBUQUERQUE PEREIRA",email:"luzinete.albuquerque@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MARCIA CEDRO DE SOUSA",email:"franciscasousa@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO CLADIMIR OLIVEIRA",email:"franciscocladimir@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO CLEDEUVAR XIMENES ARAUJO",email:"franciscocledeuvar@edu.sobral.ce.gov.br "},
{nome:"IVAN LENNON DA COSTA NOGUEIRA",email:"ivanlennon@edu.sobral.ce.gov.br"},
{nome:"JANIA MARIA RODRIGUES DOS SANTOS",email:"janiamaria@edu.sobral.ce.gov.br"},
{nome:"JOANA CLAUDIA FREIRE COELHO",email:"Joanaclaudia@edu.sobral.ce.gov.br"},
{nome:"KEILA PEREIRA DE LIMA",email:"keila@edu.sobral.ce.gov.br"},
{nome:"KELLY LIMA BARROSO",email:"kelly@edu.sobral.ce.gov.br"},
{nome:"MARIA ADRIANA MORORO",email:" adriana.mororo13@gmail.com"},
{nome:"MARIA DA CONCEIÇAO FARIAS SOUSA",email:"conceicao01farias@hotmail.com"},
{nome:"MARIA DAS DORES MESQUITA FEIJO",email:"mariafeijo@edu.sobral.ce.gov.br"},
{nome:"MARIA LUCIMAR DO NASCIMENTO PAIVA",email:"marialuciamar@edu.sobral.ce.gov.br"},
{nome:"NAIARA CAVALCANTE DE ALBUQUERQUE",email:"naiara@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDA NONATA BATISTA DE OLIVEIRA",email:"raimundanonata@edu.sobral.ce.gov.br"},
{nome:"SILVANA DOS SANTOS BENTO",email:"silvanasantos@edu.sobral.ce.gov.br"},
{nome:"THAISA FERREIRA MUNIZ",email:"thaisa@edu.sobral.ce.gov.br"},
{nome:"DANIELE LIRA CAVALCANTE",email:"daniele@edu.sobral.ce.gov.br"},
{nome:"VERONICA MARTINS MORAIS",email:"veronicam@edu.sobral.ce.gov.br"},
{nome:"JOSIANE LIMA DE ARRUDA",email:"josiarruda11@gmail.com"},
{nome:"CLAYTIANE RIBEIRO DA SILVA",email:"claytianer@gmail.com"},
{nome:"SEBASTIÃO DOMINGOS DE SOUZA",email:"sebastiaod164@gmail.com"},
{nome:"GREICIANE DE SOUSA",email:"greicemenezesdesousa@gmail.com"},
{nome:"APOLONIA MACHADO DA SILVA",email:"apoloniasilva789@gmail.com"},
{nome:"ADRIANA DE AGUIAR TORRES",email:"adrianaatorres0@gmail.com"},
{nome:"AGUIDA PAULA DUARTE BRITO",email:"paula.duarte.brito@live.com"},
{nome:"ANA PAULA DA SILVA FERREIRA",email:"paula.silvaferreira2020@gmail.com"},
{nome:"ANTONIA JOSIMAR DA COSTA",email:"cjosimar092@gmail.com"},
{nome:"ANTONIA TANIA MATOS PEREIRA",email:"taniamatospereira@gmail.com"},
{nome:"ANTONIA VERA SILVA DOS SANTOS",email:"verinhasantos162@gmail.com"},
{nome:"AYLA MARIA DE ANDRADE LIMA",email:"aylaandrade06@gmail.com"},
{nome:"BENEDITA KELLY PONTES DA SILVA",email:"spontesribeiro@hotmail.com"},
{nome:"DIVINA LIRIA SOUSA COSTA",email:"costadivina07@gmail.com"},
{nome:"FERNANDO ANTONIO ARAUJO",email:"fernando.ojuara0209@hotmail.com"},
{nome:"FRANCISCA MARIA BEZERRA ALVES",email:"francisca jaibaras1234@bol.com.br"},
{nome:"JEOVANA SILVA AZEVEDO",email:"jeovanasilvaazevedo.08@gmail.com"},
{nome:"MARIA DARLENE DA COSTA",email:"costadarlene77@gmail.com"},
{nome:"MARIA MAIANA DE LIMA TORRES",email:"torresmaiana781@gmail.com"},
{nome:"MARIA VALCILENE DE AZEVEDO DA PONTE",email:"valcileneazevedo26@gmail.com"},
{nome:"MARIA VILMA LOPES DO NASCIMENTO",email:"vilmalopesjaibaras@outlook"},
{nome:"RAIMUNDO NONATO ALEXANDRE FILHO",email:"natim-real@hotmail.com"},
{nome:"SOLANGE DE MARIA CHAVES CAVALCANTE",email:"cavalcantesolange703@gmail.com"},
{nome:"SORAIA BASTOS BARROSO",email:"soraiabastos13@gmail.com"},
{nome:"MARIA DE FATIMA GOMES APOLIANO",email:"maria.apoliano@edu.sobral.ce.gov.br"},
{nome:"SOLANGE MESQUITA BALBINO",email:"solange.balbino@edu.sobral.ce.gov.br"},
{nome:"JULIANA ALVES DE SOUSA",email:"juliana.sousa@edu.sobral.ce.gov.br"},
{nome:"EDINEUDA BEZERRA",email:"edineuda.bezerra@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MARIA TEIXEIRA DOS SANTOS",email:"francisca.maria@edu.sobral.ce.gov.br"},
{nome:"EDINEUDA BEZERRA",email:"edineuda.bezerra@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MARIA VASCONCELOS QUARIGUASI AUZIER",email:"franciscamariavqa@gmail.com"},
{nome:"ADINELIA DE FATIMA SILVA CANTANHEDE",email:"adinelia.cantanhede@edu.sobral.ce.gov.br"},
{nome:"ADRIANA PAULA CARVALHO",email:"adriana.carvalho@edu.sobral.ce.gov.br"},
{nome:"ANA CARLA CASTRO SOUSA",email:"carla.castro@edu.sobral.ce.gov.br"},
{nome:"ANA LUCIA DE JESUS",email:"ana.jesus@edu.sobral.ce.gov.br"},
{nome:"ANA PAULA FROTA DE SOUZA",email:"paula.souza@edu.sobral.ce.gov.br"},
{nome:"ANA SERGIA TREVIA MOURA",email:"ana.moura@edu.sobral.ce.gov.br"},
{nome:"CRISLEYANE DA SILVA TOMAIS",email:"crisleyane.tomais@edu.sobral.ce.gov.br"},
{nome:"ELIZABETE OLIMPIO SERPA MENDONCA",email:"elizabete.mendonca@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO NEUTON CORDEIRO DUARTE",email:"neuton.duarte@edu.sobral.ce.gov.br"},
{nome:"GAUGANHA MARIA SOUSA VASCONCELOS",email:"gauganha.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"GEISA MARIA VASCONCELOS MARQUES",email:"geisa.marques@edu.sobral.ce.gov.br"},
{nome:"JACIRA RIPARDO XAVIER",email:"jacira.ripardo@edu.sobral.ce.gov.br"},
{nome:"JOCILANE DE MESQUITA ALBUQUERQUE",email:"jocilane@edu.sobral.ce.gov.br"},
{nome:"KLEBER VIEIRA MANCO",email:"kleber.manco@edu.sobral.ce.gov.br"},
{nome:"LIVIA MARIA LIRA PONTES",email:"livia.pontes@edu.sobral.ce.gov.br"},
{nome:"LUCIANA LIMA ARAGAO",email:"luciana.aragao@edu.sobral.ce.gov.br"},
{nome:"LUCICLEIDE ROMAO SILVA",email:"lucicleide.silva@edu.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEICAO FERNANDES PORTELA BRITO",email:"maria.fernandes@edu.sobral.ce.gov.br"},
{nome:"NAGILA MAGALHAES LUCAS",email:"nagila.lucas@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDO NONATO COUTINHO",email:"raimundo.coutinho@edu.sobral.ce.gov.br"},
{nome:"SAMYLA NASCIMENTO DE SOUSA",email:"samyla.sousa@edu.sobral.ce.gov.br"},
{nome:"Candida Andrea de Mesquita Mendes",email:"candida.mendes@edu.sobral.ce.gov.br"},
{nome:"Danielle Maria Menezes de Sousa",email:"danielle.sousa@edu.sobral.ce.gov.br"},
{nome:"Eliane Monte Barboza Paiva",email:"eliane.paiva@edu.sobral.ce.gov.br"},
{nome:"Samara da Silva",email:"samara@edu.sobral.ce.gov.br"},
{nome:"Sinara Nascimento do Carmo",email:"sinara.carmo@edu.sobral.ce.gov.br"},
{nome:"Jose Aristeu do Nascimento",email:"jose.nascimento@edu.sobral.ce.gov.br"},
{nome:"Sinara Nascimento do Carmo",email:"sinara.carmo@edu.sobral.ce.gov.br"},
{nome:"Glauciana Ferreira Carneiro Lopes",email:"glauciana.lopes@edu.sobral.ce.gov.br"},
{nome:"Adriana Barbosa do Nascimento",email:"adriana.nascimento@edu.sobral.ce.gov.br"},
{nome:"Maria Dilma Monte",email:"maria.monte@edu.sobral.ce.gov.br"},
{nome:"Helenilda Araujo do Monte",email:"helenilda.monte@edu.sobral.ce.gov.br"},
{nome:"Raimunda Célia Linhares Ponte",email:"raimunda.ponte@edu.sobral.ce.gov.br"},
{nome:"Janderly do Monte de Araújo",email:"janderly.araujo@edu.sobral.ce.gov.br"},
{nome:"Janderly do Monte de Araújo",email:"janderly.araujo@edu.sobral.ce.gov.br"},
{nome:"Maria Dilma Monte",email:"maria.monte@edu.sobral.ce.gov.br"},
{nome:"Silvelane Maria Azevedo Lima",email:"silvelane.lima@edu.sobral.ce.gov.br"},
{nome:"Maria Luciana Ponte Parente",email:"luciana.parente@edu.sobral.ce.gov.br"},
{nome:"Silvelane Maria Azevedo Lima",email:"silvelane.lima@edu.sobral.ce.gov.br"},
{nome:"Maria Luciana Ponte Parente",email:"luciana.parente@edu.sobral.ce.gov.br"},
{nome:"Romario Freire Alcantara",email:"romario.alcantara@edu.sobral.ce.gov.br"},
{nome:"Antonia Aline Gama de Oliveira",email:"antonia.oliviera@edu.sobral.ce.gov.br"},
{nome:"Kleiton Arruda Sales",email:"keliton.sales@edu.sobral.ce.gov.br"},
{nome:"Francisco do Carmo Silva",email:"francisco.carmo@edu.sobral.ce.gov.br"},
{nome:"Francisco Washington Rodrigues de Farias",email:"francisco.farias@edu.sobral.ce.gov.br"},
{nome:"Raphael Gomes Vale",email:"raphael.vale@edu.sobral.ce.gov.br"},
{nome:"Zélia Caetano dos Santos Silva",email:"zelia.silva@edu.sobral.ce.gov.br"},
{nome:"SANDRA MARIA DA CONCEIÇÃO DA SILVA",email:"sandra.silva@edu.sobral.ce.gov.br"},
{nome:"FERNANDA RODRIGUES DA SILVA",email:"fernanda.silva@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDA ELAYNE RODRIGUES SOARES",email:"raimunda.soares@edu.sobral.ce.gov.br"},
{nome:"CHRISTOPHER MOURA MONTEZUMA",email:"christopher.montezuma@edu.sobral.ce.gov.br"},
{nome:"JOSE ALVES CARNEIRO",email:"jose.carneiro@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO EDSON DUARTE DE SOUSA",email:"edson.sousa@edu.sobral.ce.gov.br"},
{nome:"ELIZAMAR GUILHERME CONSTANCIO",email:"elizamar.constancio@edu.sobral.ce.gov.br"},
{nome:"TIAGO DE LIMA SILVA",email:"tiago.silva@edu.sobral.ce..gov.br"},
{nome:"ANA PAULA CRUZ DO NASCIMENTO",email:"ana.nascimento@edu.sobral.ce.gov.br"},
{nome:"MAGALI SANTOS MOTA",email:"magali.mota@edu.sobral.ce.gov.br"},
{nome:"PATRICIA ALBUQUERQUE SOUSA",email:"patricia.albuquerque@edu.sobral.ce.gov.br"},
{nome:"LUZIA DO NASCIMENTO GOMES",email:"luzia.gomes@edu.sobral.ce.gov.br"},
{nome:"MARIA LUCIA DA COSTA",email:"maria.lucia.costa@edu.sobral.ce.gov.br"},
{nome:"ANA CLAUDIA GRACIANO DE HOLANDA",email:"ana.holanda@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MARIANA DA SILVA NUNES",email:"mariananunes.seducsobral@gmail.com"},
{nome:"THAYNAH VASCONCELOS ARAGAO",email:"thaynah.aragao@edu.sobral.ce.gov.br"},
{nome:"ANTONIA EDILMA MOREIRA ALBUQUERQUE",email:"antonia.albuquerque@edu.sobral.ce.gov.br"},
{nome:"SANDRINE MENEZES PONTE",email:"sandrine.ponte@edu.sobral.ce.gov.br"},
{nome:"VERA LUCIA DE SOUSA FERNANDES",email:"vera.fernandes@edu.sobral.ce.gov.br"},
{nome:"MARIA AUXILIADORA CAVALCANTE FERREIRA",email:"auxiliadora.ferreira@edu.sobral.ce.gov.br"},
{nome:"ANA PAULA RODRIGUES DA SILVA",email:"paula.silva@edu.sobral.ce.gov.br"},
{nome:"MARIA DO SOCORRO SOUSA SILVA",email:"socorro.sousa@edu.sobral.ce.gov.br"},
{nome:"CLAUDIA VERAS DOS SANTOS",email:"claudia.santos@edu.sobral.ce.gov.br"},
{nome:"GLAUCIANE FEIJAO DO NASCIMENTO",email:"glauciane.nascimento@edu.sobral.ce.gov.br"},
{nome:"MARIA ALZENIRA MARQUES BARROSO",email:"maria.barroso@edu.sobral.ce.gov.br"},
{nome:"VALNEIDE DE ARAUJO FELIX",email:"valneide.felix@edu.sobral.ce.gov.br"},
{nome:"MARIA AUSTRELINDA DE OLIVEIRA FERNANDES",email:"austrelinda.fernandes@edu.sobral.ce.gov.br"},
{nome:"ROSA MARIA FERREIRA DO NASCIMENTO",email:"rosa.ferreira.nascimento@edu.sobral.ce.gov.br"},
{nome:"CAMILA ALVES DA SILVA",email:"camila.silva@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO NEWTON DO NASCIMENTO SANTOS",email:"newton@edu.sobral.ce.gov.br"},
{nome:"ADELAIDE ALINE PORTELA ALMEIDA",email:"adelaide.almeida@edu.sobral.ce.gov.br"},
{nome:"GRACE DONATO DE MOURA",email:"grace.donato@edu.sobral.ce.gov.br"},
{nome:"KERGIANE MENESES PRADO NEPOMUCENO",email:"kergiane.nepomuceno@edu.sobral.ce.gov.br"},
{nome:"SILVIA HELENA AGUIAR DA SILVA RIBEIRO",email:"silvia.ribeiro@edu.sobral.ce.gov.br"},
{nome:"ANA PATRICIA CARNEIRO DE LIMA",email:"patricia.lima@edu.sobral.ce.gov.br"},
{nome:"SILVANA SILVA DE SOUSA ",email:"silvana.silva@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MARQUES DE SOUSA",email:"francisca.marques@edu.sobral.ce.gov.br"},
{nome:"FABIANE VASCONCELOS MARQUES ",email:"fabiane.marques@edu.sobral.ce.gov.br"},
{nome:"HERTAN BRUNO NASCIMENTO DE ARAUJO ",email:"hertan.araujo@edu.sobral.ce.gov.br"},
{nome:"MANUEL ROMERO FURTADO DE SOUSA ",email:"manuel.romero@edu.sobral.ce.gov.br"},
{nome:"EVILANE DA SILVA LINO",email:"evilane.lino@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDA NONATA SARAIVA PINTO",email:"raimunda.pinto@edu.sobral.ce.gov.br"},
{nome:"LUIZA ROZIANE ALVES BRAGA",email:"luiza.braga@edu.sobral.ce.gov.br"},
{nome:"ANA BEATRIZ RODRIGUES PINTO",email:"ana.pinto@edu.sobral.ce.gov.br"},
{nome:"DANIELE MESQUITA GERONIMO",email:"daniele.geronimo@edu.sobral.ce.gov.br"},
{nome:"ARNOBIO BARBOZA AVILA",email:"arnobio.avila@edu.sobral.ce.gov.br"},
{nome:"JORGE HALANDERSON AVILA MAGALHÃES",email:"jorge.magalhaes@edu.sobral.ce.gov.br"},
{nome:"ALEXSANDRA FERREIRA RODRIGUES",email:"alexsandra.rodrigues@edu.sobral.ce.gov.br"},
{nome:"ANA CLEBIA ARAÚJO BRANDÃO",email:"ana.brandao@edu.sobral.ce.gov.br"},
{nome:"ANTONIA APARECIDA FERREIRA RODRIGUES",email:"antonia.rodrigues@edu.sobral.ce.gov.br"},
{nome:"ANTONIO DUARTE RODRIGUES",email:"antonio.rodrigues@edu.sobral.ce.gov.br"},
{nome:"GLEIDSON MENDES MELO",email:"gleidson.melo@edu.sobral.ce.gov.br"},
{nome:"MÁGNA BRAGA OLIVEIRA MAGALHÃES",email:"magna.magalhaes@edu.sobral.ce.gov.br"},
{nome:"ELENILDA DA SILVA DO NASCIMENTO",email:"elenildanascimento@edu.sobral.ce.gov.br"},
{nome:"MARIA GORETE FAUSTINO",email:"mariafaustino@edu.sobral.ce.gov.br"},
{nome:"MARIA JARINA BEZERRA ARAGAO",email:"mariaaragao@edu.sobral.ce.gov.br"},
{nome:"SARA ROCHA SILVA",email:"sarasilva@edu.sobral.ce.gov.br"},
{nome:"ALCINEIDE PINTO DE SOUZA",email:"alcineidesouza@edu.sobral.ce.gov.br"},
{nome:"EUZENY MAMEDE AMORIM",email:"euzenyamorim@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO REGINALDO ARAÚJO DE SOUSA",email:"franciscosousa@edu.sobral.ce.gov.br"},
{nome:"GENILDA RIPARDO DA PONTE",email:"genildaponte@edu.sobral.ce.gov.br"},
{nome:"MARIA DE FÁTIMA FERNANDES DE AGUIAR PARENTE",email:"mariaparente@edu.sobral.ce.gov.br"},
{nome:"GENOVINA MARIA PEREIRA ANDRADE",email:"genovinaandrade@edu.sobral.ce.gov.br"},
{nome:"IRENE DE MATOS DE SOUSA",email:"irenesousa@edu.sobral.ce.gov.br"},
{nome:"KÁTIA CRISTINA GOMES LINO",email:"katialino@edu.sobral.ce.gov.br"},
{nome:"LUZIA TRINDADE FRANCA",email:"luziafranca@edu.sobral.ce.gov.br"},
{nome:"SILVANA SILVA DE SOUZA",email:"silvanasouza@edu.sobral.ce.gov.br"},
{nome:"EDUARDO RODRIGUES DE SOUSA",email:"eduardosousa@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA MIRNA DE ALBUQUERQUE SILVA",email:"mirna@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO FREIRE ALCANTARA FILHO ",email:"franciscofilho@edu.sobral.ce.gov.br"},
{nome:"JOSIEL MOTA PEREIRA",email:"josielpereira@edu.sobral.ce.gov.br"},
{nome:"LUZINETE CHAGAS NASCIMENTO",email:"luzinetenascimento@edu.sobral.ce.gov.br"},
{nome:"ANGELICA MARIA DE FARIAS",email:"angelicafarias@edu.sobral.ce.gov.br"},
{nome:"JOSELANDIA DE SOUSA OLIVEIRA",email:"joselandiaoliveira@edu.sobral.ce.gov.br"},
{nome:"MARIA DO CARMO DE PAULO DO NASCIMENTO",email:"marianascimento@edu.sobral.ce.gov.br"},
{nome:"TERESINHA LIBERATO VIANA",email:"teresinhaviana@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA PINTO TAVARES ARAGÃO",email:"francisca.pinto@edu.sobral.ce.gov.br"},
{nome:"ANTONIO RAMON FIRMO DA COSTA",email:"antonio.costa@edu.sobral.ce.gov.br"},
{nome:"MARIA DO CARMO FARIAS BRITO",email:"maria.brito@edu.sobral.ce.gov.br"},
{nome:"ANTONIO PAIVA DA SILVA",email:"antonio.silva@edu.sobral.ce.gov.br"},
{nome:"PAULO RUBENS DE ARAUJO GAMELHEIRA",email:"paulo.gamelheira@edu.sobral.ce.gov.br"},
{nome:"MARCIA CRISTINA PAIVA GOMES",email:"marcia.gomes@edu.sobral.ce.gov.br"},
{nome:"CARLOS GIOVANO CUNHA MENDONÇA",email:"carlos.mendonca@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA RODRIGUES SAMPAIO",email:"franciscar@edu.sobral.ce.gov.br"},
{nome:"ENEIDA BEZERRA CARVALHO SOEIRO",email:"eneida.soeiro@edu.sobral.ce.gov.br"},
{nome:"IZAIRA VASCONCELOS NEPOMUCENO",email:"izaira.nepomuceno@edu.sobral.ce.gov.br"},
{nome:"ANTONIA ROSEMEIRE MORAES RIBEIRO PORTELA",email:"antonia.portela@edu.sobral.ce.gov.br"},
{nome:"TEREZINHA DE JESUS DO NASCIMENTO",email:"terezinha.nascimento@edu.sobral.ce.gov.br"},
{nome:"ANTONIO MARCOS FARIAS CASTELO BRANCO",email:"antonio.farias@edu.sobral.ce.gov.br"},
{nome:"NILTON DO VALE CAVALCANTE",email:"nilton.cavalcante@edu.sobral.ce.gov.br"},
{nome:"WESLEY MENDES LOPES DA SILVA",email:"wesley.silva@edu.sobral.ce.gov.br"},
{nome:"VANUZIA BRITO LIMA",email:"vanuzia.lima@edu.sobral.ce.gov.br"},
{nome:"FERNANDO LOPES FERREIRA",email:"fernando.ferreira@edu.sobral.ce.gov.br"},
{nome:"SILVANA MARIA DE SOUSA",email:"silvana.sousa@edu.sobral.ce.gov.br"},
{nome:"KALLVYANNE MARIA FREIRE CAVALCANTE",email:"kallvyanne.cavalcante@edu.sobral.ce.gov.br"},
{nome:"CAETANO DA PONTE MACHADO",email:"caetano.machado@edu.sobral.ce.gov.br"},
{nome:"MARIA DE LOURDES NASCIMENTO LOPES",email:"maria.lourdes@edu.sobral.ce.gov.br"},
{nome:"JUSCIELTON MARQUES MONTE",email:"juscielton.monte@edu.sobral.ce.gov.br"},
{nome:"GEORGIA DA SILVA CHAGAS",email:"georgia.chagas@edu.sobral.ce.gov.br"},
{nome:"FIAMMA DARLEN GOMES DE SOUZA ",email:"fiamma.souza@edu.sobral.ce.gov.br"},
{nome:"CASSILDA FARIAS SENA",email:"cassilda.sena@edu.sobral.ce.gov.br"},
{nome:"ANTONIO ROBERTO SOARES CAVALCANTE",email:"antonio.cavalcante@edu.sobral.ce.gov.br"},
{nome:"MARIA CLEA MATOS LOPES",email:"maria.lopes@edu.sobral.ce.gov.br"},
{nome:"CLEIDE DO NASCIMENTO CARLOS",email:"cleide.carlos@edu.sobral.ce.gov.br"},
{nome:"NATANAEL ROMAO GADELHA",email:"natanael.gadelha@edu.sobral.ce.gov.br"},
{nome:"AMANDA IRIS ARAGÃO SANTOS",email:"amanda.santos@edu.sobral.ce.gov.br"},
{nome:"JOSÉ MARIO FROTA FONTELES",email:"jose.fonteles@edu.sobral.ce.gov.br"},
{nome:"JOSÉ EDUARDO DE MESQUITA",email:"jose.mesquita@edu.sobral.ce.gov.br"},
{nome:"MARIA DJACYRA COSTA CAVALCANTE",email:"maria.cavalcante@edu.sobral.ce.gov.br"},
{nome:"DANIEL  DO NASCIMENTO RODRIGUES",email:"daniel.rodrigues@edu.sobral.ce.gov.br"},
{nome:"ELIZABETH CRISTINA RIBEIRO PONTES",email:"elizabeth.pontes@edu.sobral.ce.gov.br"},
{nome:"ANTONIA ALCINETE MARCIEL VICENTE",email:"antonia.vicente@edu.sobral.ce.gov.br"},
{nome:"ITALA MARIA RIPARDO NEVES",email:"itala.neves@edu.sobral.ce.gov.br"},
{nome:"SILVANA LINHARES SALES",email:"silvana.sales@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO SAMUEL  SOUSA SILVA",email:"samuel.silva@edu.sobral.ce.gov.br"},
{nome:"MARIA WILMA DUARTE PONTE",email:"wilma.ponte@edu.sobral.ce.gov.br"},
{nome:"NIVIA MARIA  PEREIRA  MARTINS ",email:"nivia.pereira@edu.sobral.ce.gov.br"},
{nome:"MARIA IRISMAR SOUSA",email:"maria.irismar.sousa@edu.sobral.ce.gov.br"},
{nome:"MARIA ELIZETE TEIXEIRA GONÇALVES",email:"maria.elizete@edu.sobral.ce.gov.br"},
{nome:"ROSILÁNINA MARIA DE VASCONCELOS",email:"rosilanina.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"NEYLA CRISTINA SILVA DA COSTA",email:"neyla.costa@edu.sobral.ce.gov.br"},
{nome:"LIDUINA SILVINO DE SALES",email:"liduina.sales@edu.sobral.ce.gov.br"},
{nome:"ANTONIO WESCLEY BARROS DUARTE",email:"wescley@edu.sobral.ce.gov.br"},
{nome:"BRUNO DA COSTA OLIVEIRA",email:"bruno.costa@edu.sobral.ce.gov.br"},
{nome:"CAMILO SOUSA CAVALCANTE LETRAS",email:"camilo.sousa@educ.sobral.gov.br"},
{nome:"EDILAINY MARIA DOS SANTOS FARIAS",email:"edilainy@edu.sobral.ce.gov.br"},
{nome:"Francisca Rogelma Alves",email:"rogelma.alves@edu.sobral.ce.gov.br"},
{nome:"MANUEL FERNANDES DE ARAUJO NETO",email:"manuel.fernandes@edu.sobral.ce.gov.br"},
{nome:"MARIA ALZENIRA MARQUES BARROSO",email:"maria.alzenira@edu.sobral.ce.gov.br"},
{nome:"NATANAEL ROMÃO GADELHA",email:"natanael.gadelha@edu.sobral.ce.gov.br"},
{nome:"PEDRO ARILSON PINHEIRO RODRIGUES",email:"pedro.arilson@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDO NONATO DA SILVA COSTA",email:"raimundo.silva@edu.sobral.ce.gov.br"},
{nome:"SELMA MARIA VIANA",email:"selma.maria@edu.sobral.ce.gov.br"},
{nome:"VERONICA DE BRITO LIMA",email:"veronica.brito@edu.sobral.ce.gov.br"},
{nome:"ALEXSANDRA MARIA COELHO SALES",email:"alexsandra.sales@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA SHIRLEANE FERREIRA ARAGAO",email:"franciscashirlene@edu.sobral.ce.gov.br"},
{nome:"ANA CARMEM PAULA PESSOA DIAS ANDRADE",email:"ana.carmem@edu.sobral.ce.gov.br"},
{nome:"FABIOLA SILVA CARNEIRO",email:"fabiola.carneiro@edu.sobral.ce.gov.br"},
{nome:"SILVANA BRAGA CARNEIRO",email:"silvana.carneiro@edu.sobral.ce.gov.br"},
{nome:"NOEME SOUZA IBIAPINA",email:"noeme.ibiapina@edu.sobral.ce.gov.br"},
{nome:"ROSANGELA MARIA DE SOUZA",email:"rosangela.souza@edu.sobral.ce.gov.br"},
{nome:"IRACEMA AGUIAR DA CRUZ",email:"iracema.cruz@edu.sobral.ce.gov.br"},
{nome:"MARIA DE FATIMA LOPES VASCONCELOS",email:"maria.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"ANA LUCIA MESQUITA FROTA",email:"ana.frota@edu.sobral.ce.gov.br"},
{nome:"ANA MARCIA DE OLIVEIRA CARVALHO ARAGAO",email:"ana.marcia@edu.sobral.ce.gov.br"},
{nome:"SAMARA RIBEIRO DE SOUSA",email:"samara.sousa@edu.sobral.ce.gov.br"},
{nome:"ROSA MARIA SOUSA MENDES",email:"rosa.mendes@edu.sobral.ce.gov.br"},
{nome:"ROSANGELA MARIA MENDES DA SILVA",email:"rosangela.maria@edu.sobral.ce.gov.br"},
{nome:"KELLIANE FERREIRA LIMA",email:"Kelliane.lima@edu.sobral.ce.gov.br"},
{nome:"TAMIRES KELCIA DO NASCIMENTO DE OLIVEIRA",email:"tamires.oliveira@edu.sobral.ce.gov.br"},
{nome:"ANA CARLA ARAUJO SOUSA VIDAL",email:"carlavidal190@hotmail.com"},
{nome:"JOSEFA COSTA SILVA",email:"joalegria833@gmail.com"},
{nome:"ENAILE MARIA MARTINS MORORO",email:"enaile.mororo@edu.sobral.ce.gov.br"},
{nome:"ANA CLEVIA ROMÃO SILVA",email:"Clevia.silva@edu.sobral.ce.gov.br"},
{nome:"JOSE OTAVIANO LOPES FILHO",email:"otavianolopes62@gmail.com "},
{nome:"FRANCISCO ROBERIO LINHARES RODRIGUES ",email:"roberio@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO ITALO BERNARDINO DO NASCIMENTO",email:"italo.nascimento@edu.ce.gov.br"},
{nome:"DALVA ECILA DE AGUIAR FERNANDES",email:"dalva.ecila09@gmail.com"},
{nome:"RENYELLY FERNANDES DE SOUSA",email:"renyelly@edu.sobral.ce.gov.br"},
{nome:"MARIA DA CONCEIÇÃO RIBEIRO ARAGÃO",email:"conceicao.ribeiro@edu.sobral.ce.gov.br"},
{nome:"ISIANE ALVES DE OLIVEIRA",email:"isiane@edu.sobral.ce.gov.br"},
{nome:"ANA CLAUDIA SILVA SILVINO",email:"claudia.silvino@edu.sobral.ce.gov.br"},
{nome:"ANA LEDA LIBERATO DIAS",email:"analedaliberato@gmail.com"},
{nome:"MARIA IRENE TEIXEIRA FERREIRA",email:"irene.ferreira@edu.sobral.ce.gov.br"},
{nome:"ANNE VALÉRIA SERAFIM",email:"anne.v.serafim@gmail.com"},
{nome:"ANTONIO ACÁCIO AGUIAR GOMES",email:"acaciogomes@live.com"},
{nome:"DANIELLE LUIZE SANTOS DE OLIVEIRA",email:"daniell_oliveira93@outlook.com"},
{nome:"FRANCISCO CÉSAR RODRIGUES",email:"cesar.vidasima@yahoo.com.br"},
{nome:"MÁGDALA HÉVELLIN SOUSA DUARTE",email:"maghevellinsd@hotmail.com"},
{nome:"MISAEL DO NASCIMENTO OLIVEIRA",email:"misael_oliveira@hotmail.com"},
{nome:"NATÁLIA MARIA DE CARVALHO",email:"nataliacarvalhonc@gmail.com"},
{nome:"RARISSON ALEXANDRE FELIX",email:"rarissonaf@gmail.com"},
{nome:"SUIANE VIRGINIA PEREIRA LOIOLA",email:"suianeloiola@gmail.com"},
{nome:"ANTONIA NOELIA LOPES ROCHA",email:"profndelia50@gmail.com"},
{nome:"EMANUELA MATOS FERREIRA",email:"emanuela.esfapege@gmail.com"},
{nome:"FLÁVIO LOIOLA FROTA",email:"flaviofrota4@gmail.com"},
{nome:"FRANCISCO ALLAN SOUSA SALES",email:"allan_croata@hotmail.com"},
{nome:"KARLYANE PIMENTA DE CARVALHO COSTA",email:"karlyanepimenta721@gmail.com"},
{nome:"LUCE PATRÍCIA VASCONCELOS DE ALBUQUERQUE ",email:"lupatvaal@hotmail.com"},
{nome:"MARIA IVONETE BRAZ SOUZA",email:"ivonetebrazz@hotmail.com"},
{nome:"PATRÍCIA VALÉRIA FARIAS PRADO",email:"patyvaleriafp@yahoo.com.br"},
{nome:"ANA JULIA DE SOUSA PONTE",email:"julia.ponte@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA SHIRLEY ARAÚJO FERREIRA",email:"shirley.araujo@edu.sobral.ce.gov.br"},
{nome:"ISABEL CRISTINA LOPES DE MORAIS",email:"isabel.morais@edu.sobral.ce.gov.br"},
{nome:"ERIKA CHAVIER GUIMARES TURCATO",email:"erika.turcato@edu.sobral.ce.gov.br"},
{nome:"MARIA PRISCILA DA COSTA DA SILVA",email:"maria.silva@edu.sobral.ce.gov.br"},
{nome:"TICIANY MARIA ALVES PEREIRA",email:"ticiany.pereira@edu.sobral.ce.gov.br"},
{nome:"ANTONIA ELISANGELA MOUTA PAIVA",email:"antonia.paiva@edu.sobral.ce.gov.br"},
{nome:"MARIA TAIS RODRIGUES ARRUDA",email:"tais.arruda@edu.sobral.ce.gov.br"},
{nome:"MARIA VALERIA AGUIAR PESSOA",email:"maria.pessoa@edu.sobral.ce.gov.br"},
{nome:"ROBERTA DE JESUS FERREIRA SANTOS",email:"roberta.santos@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA VALDELINA DE FROTA COSTA",email:"francisca.valdelina@edu.sobral.ce.gov.br"},
{nome:"SALETE RODRIGUES CRUZ",email:"salete.cruz@edu.sobral.ce.gov.br"},
{nome:"MARIA VALDENISA DUARTE DE OLIVEIRA",email:"maria.oliveira@edu.sobral.ce.gov.br"},
{nome:"VALDERINA FARRAPO COSTA",email:"valderina.costa@edu.sobral.ce.gov.br"},
{nome:"ANA MARIA CARNEIRO",email:"ana.carneiro@edu.sobral.ce.gov.br"},
{nome:"ANA PATRICIA LINHARES ALVES",email:"ana.alves@edu.sobral.ce.gov.br"},
{nome:"BETTY LEE DO NASCIMENTO SANTANA MARQUES",email:"betty.santana@edu.sobral.ce.gov.br"},
{nome:"ROSA MARIA PAULINO DE SOUSA",email:"rosa.paulino@edu.sobral.ce.gov.br"},
{nome:"JUSSYELLY MARIA DO NASCIMENTO CASTRO",email:"jussyelycastro@edu.sobral.ce.gov.br"},
{nome:"MARIA LAURA DE LIMA CONSTANCIO",email:"maria.constancio@edu.sobral.ce.gov.br"},
{nome:"ROCHELE PENHA FLORENCIO",email:"rochele.florencio@edu.sobral.ce.gov.br"},
{nome:"MARIA LUCINA PEREIRA PEDROSA",email:"maria.pedrosa@edu.sobral.ce.gov.br"},
{nome:"ALINE CRISTINA DIAS RODRIGUES",email:"aline.rodrigues@edu.sobral.ce.gov.br"},
{nome:"CAMILA FARIAS DO MONTE",email:"camila.monte@edu.sobral.ce.gov.br"},
{nome:"MARIA TATIANE PEREIRA PEDROSA",email:"tatiana.pedrosa@edu.sobral.ce.gov.br"},
{nome:"MARCIA GOMES NASCIMENTO",email:"marcia.nascimento@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA VANDA DA SILVA",email:"francisca.silva@edu.sobral.ce.gov.br"},
{nome:"PAULA MARIA SILVA DO NASCIMENTO",email:"paulinhaslw@hotmail.com"},
{nome:"ANTONIA BRUNA BASTOS DO NASCIMENTO",email:"brunaprof7@hotmail.com"},
{nome:"KELLY ABREU SILVA",email:"kellynhaabreu@hotmail.com"},
{nome:"FRANCISCO WELLINGTON ARRUDA LINHARES",email:"ws_nite@hotmail.com"},
{nome:"MARIA DO AMPARO LINHARES",email:"amparinhalinhares1234@gmail.com"},
{nome:"GRACE DONATO DE MOURA",email:"grace@edu.sobral.ce.gov.br"},
{nome:"ISABELE MUNIZ FERREIRA",email:"isabele.ferreira@edu.sobral.ce.gov.br"},
{nome:"JORGIANE DE SOUZA GAMELEIRA",email:"jorgiane.gameleira@edu.sobral.ce.gov.br"},
{nome:"KAROLAYNE SUELLEN CAVALCANTE SILVA",email:"karolayne.silva@edu.sobral.ce.gov.br"},
{nome:"NAYARA SILVA DE OLIVEIRA",email:"nayara.oliveira@edu.sobral.ce.gov.br"},
{nome:"SANDRA MARIA DOS REIS FEIJÃO",email:"sandra.feijao@edu.sobral.ce.gov.br"},
{nome:"SEBASTIÃO SOARES DE SOUSA JUNIOR",email:"sebastiao.junior@edu.sobral.ce.gov.br"},
{nome:"ANTÔNIO CARLOS CARREIRO CHAVES",email:"antonio.chaves@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO DANIEL ALVES CAMPOS",email:"francisco.campos@edu.sobral.ce.gov.br"},
{nome:"JOANA KARLA CARDOSO CRUZ DE ANDRADE ",email:"joana.andrade@edu.sobral.ce.gov.br"},
{nome:"JOSE EDUARDO DE MESQUITA",email:"jose.eduardo@edu.sobral.ce.gov.br"},
{nome:"MARIA CRISTIANE GOMES",email:"cristiane.gomes@edu.sobral.ce.gov.br"},
{nome:"RAIMUNDO CLEHILTON MARQUES SOUSA ",email:"clehilton.sousa@edu.sobral.ce.gov.br"},
{nome:"Catia Maria de Sena ",email:"catia.sena@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA VERONICA RODRIGUES DUARTE",email:"veronica.duarte@edu.sobral.ce.gov.br"},
{nome:"Maria Jania de Sousa",email:"maria.jania@edu.sobral.ce.gov.br"},
{nome:"Antonia de Fátima Campos",email:"antonia.campos@edu.sobral.ce.gov.br"},
{nome:"Antonia Eli Ferreira Lima Moura ",email:"antonia.moura@edu.sobral.ce.gov.br"},
{nome:"Emanuel Alisson Damasceno",email:"emanuel@edu.sobral.ce.gov.br"},
{nome:"Kelciane de Fátima Portela Vieira",email:"Kelciane.vieira@edu.sobral.ce.gov.br"},
{nome:"Marcela Portela Pontes Correia ",email:"marcela.correia@edu.sobral.ce.gov.br"},
{nome:"Mariana Cristina Teles Araújo",email:"Mariana.araujo@edu.sobral.ce.gov.br"},
{nome:"Maria Marcia Lima ",email:"maria.marcia@edu.sobral.ce.gov.br"},
{nome:"Zeneide Bento Albuquerque",email:"zeneide.albuquerque@edu.sobral.ce.gov.br"},
{nome:"ANGELA MARIA CARNEIRO ARAUJO",email:"angela.araujo@edu.sobral.ce.gov.br"},
{nome:"ANNE GRAZIELLE SOUZA OLIVEIRA LIESEMBERG",email:"anne.liesemberg@edu.sobral.ce.gov.br"},
{nome:"ANTONIA EXPEDIANA DE ARAÚJO ABREU",email:"antonia.abreu@edu.sobral.ce.gov.br"},
{nome:"ANTONIA FLAVIA SILVA DE AGUIAR",email:"antonia.aguiar@edu.sobral.ce.gov.br"},
{nome:"ANTONIA GRIJAELLA MESQUITA REIS",email:"antonia.reis@edu.sobral.ce.gov.br"},
{nome:"ANTONIO ELIEZIO MARTINS",email:"antonio.martins@edu.sobral.ce.gov.br"},
{nome:"CRISTIANE MENESCAL DE ALBUQUERQUE",email:"cristiane.albuquerque@edu.sobral.ce.gov.br"},
{nome:"DAIANA MARIA FÉLIX CAVALCANTE",email:"daiana.cavalcante@edu.sobral.ce.gov.br"},
{nome:"DAYANA LIMA LEITÃO DA COSTA",email:"dayana.costa@edu.sobral.ce.gov.br"},
{nome:"EDUARDO RODRIGUES DE SOUSA",email:"eduardo.rodrigues@edu.sobral.ce.gov.br"},
{nome:"ELIETE DE SOUSA VASCONCELOS",email:"eliete.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA VILMA DIAS SOUSA",email:"francisca.vilma@edu.sobral.ce.gov.br"},
{nome:"FRANCISCA WAGNA BRAGA VASCONCELOS",email:"wagna vaconscelos@hotmail.com"},
{nome:"FRANCISCO AUGUSTO RODRIGUES FERREIRA",email:"augusto.ferreira@edu.sobral.ce.gov.br"},
{nome:"FRANCISCO WELLINGTON HIGINO SOUSA",email:"francisco.wellington@edu.sobral.ce.gov.br"},
{nome:"JULYA CARNEIRO MESQUITA DE LIMA",email:"julya.lima@edu.sobral.ce.gov.br"},
{nome:"LUCIA MARIA SOUSA SILVA",email:"lucia.silva@edu.sobral.ce.gov.br"},
{nome:"LUCIANA DA SOLEDADE DE ARAÚJO CARNEIRO",email:"luciana.carneiro@edu.sobral.ce.gov.br"},
{nome:"LUCIANA MARIA ALVES",email:"luciana.maria@edu.sobral.ce.gov.br"},
{nome:"MARIA GERLENI DO CARMO DE MARIA DA SILVA",email:"maria.gerleni@edu.sobral.ce.gov.br"},
{nome:"MARIA GILVANA DO CARMO DE MARIA",email:"maria.gilvana@edu.sobral.ce.gov.br"},
{nome:"MARIA GLAUCIVANE SAMPAIO PORTELA",email:"maria.glaucivane@edu.sobral.ce.gov.br"},
{nome:"MARIA KATIUCIA CATUNDA BASTOS",email:"maria.katiucia@edu.sobral.ce.gov.br"},
{nome:"MARIA RODRIGUES DOS SANTOS",email:"maria.rodrigues.santos@edu.sobral.ce.gov.br"},
{nome:"MARIA ROMANA DE VASCONCELOS",email:"maria.romana@edu.sobral.ce.gov.br"},
{nome:"RENATA MARIA DE SOUSA",email:"renata.sousa@edu.sobral.ce.gov.br"},
{nome:"ROSINETE FEITOSA DE VASCONCELOS",email:"rosinete.vasconcelos@edu.sobral.ce.gov.br"},
{nome:"SANDRA MADEIRA DE SOUSA SILVA",email:"sandra.madeira@edu.sobral.ce.gov.br"},
{nome:"SANDRA MARIA DE ALMEIDA OLIVEIRA",email:"sandra.oliveira@edu.sobral.ce.gov.br"},
{nome:"SUELY TEODORO DE CASTRO ALMEIDA",email:"suely.almeida@edu.sobral.ce.gov.br"},
{nome:"WILDIANE GONÇALVES DO NASCIMENTO",email:"wildiane.nascimento@edu.sobral.ce.gov.br"}]
const pessoasComparar = ["CARLOS HENRIQUE PEREIRA LINS", "FRANCISCA ELBIA PAULO BORGES", "YARA RENATA DIAS DE LOIOLA", "FRANCISCA EDNA DE OLIVEIRA SILVA", "ANDREA CARDOSO DOS SANTOS ROCHA", "ANTONIA PATRICIA LIMA", "AURICELIA SANTANA DE SOUSA", "CRISTINA ANDRADE ALVES", "ELIEUDA ALVES RODRIGUES", "FERNANDA ARAGAO DE FRANCA", "JAIRANE SANTOS DE SOUSA", "MALBA REGINA PEREIRA DA SILVA", "MARIA TEREZINHA DE SOUSA ARAUJO", "MARIA ZENILDA BISPO", "NATANA MARIA RODRIGUES DAMASCENO", "NONATA MARIA XAVIER", "ANTONIA ELIZANGELA NERES LIMA", "ANDERSON ANDRE DE SOUZA", "ANTONIA DEUSILENE AGUIAR VAZ SOARES", "ANTONIA LEILA MACHADO PORTELA", "DENISE ARAGAO SOUSA", "FRANCISCA GELIANA DE ALBUQUERQUE", "FRANCISCA MIRNA DE ALBUQUERQUE SILVA", "FRANCISCO DAS CHAGAS FERREIRA CAVALCANTE", "FRANCISCO DAS CHAGAS PAULINO SAMPAIO", "JOSE GLEISON ALVES DA SILVA", "JOSE HORLANDO SABINO DE SOUSA", "JOSE OSMAR MONTEZUMA DE SOUZA", "LILIANE XIMENES PONTE", "MARCELO ANGELO DE LIMA", "MARIA DE LOURDES PARENTE", "SIBERI LINHARES DA COSTA", "VANESSA LIMA NERY OLIVEIRA", "YTAYARA RIBEIRO DE ALBUQUERQUE", "ZILMAR ALBUQUERQUE PARENTE", "MARIA DARLENE ARAUJO DO NASCIMENTO MOURA", "OSVALDO NETO DE SOUSA COSTA", "ANA CYZIA XIMENES DE MELO ARAGAO", "ELIANE EPIFANIO FERNANDES GOMES", "FLAVIA DE FATIMA MARQUES PEREIRA", "MARIA LUCIMAR PINHEIRO GONCALVES", "MARIA RUFINO CRUZ", "NEIDE MARA SAMPAIO", "MARCIA SOARES FERNANDES", "MARIA VALDENISA DUARTE DE OLIVEIRA", "JUSSYELLY MARIA DO NASCIMENTO CASTRO", "ROCHELE PENHA FLORENCIO", "BETTY LEE DO NASCIMENTO SANTANA MARQUES", "ERIKA XAVIER GUIMARAES TURCATTO", "ALINE CRISTINA DIAS RODRIGUES", "ANA JULIA DE SOUSA PONTE", "ANA MARIA CARNEIRO", "ANA PATRICIA LINHARES ALVES", "ANTONIA ELISANGELA MOUTA PAIVA", "CAMILA FARIAS DO MONTE", "FRANCISCA CARLANDIA LIMA DE SOUZA", "FRANCISCA GOMES MARQUES", "ISABEL CRISTINA LOPES DE MORAIS", "MARIA LAURA DE LIMA CONSTANCIO", "MARIA LUCINA PEREIRA PEDROSA", "MARIA PRISCILA DA COSTA DA SILVA", "MARIA TAIS RODRIGUES ARRUDA", "MARIA TATIANE PEREIRA PEDROSA", "MARIA VALDENISA DUARTE DE OLIVEIRA", "MARIA VALERIA AGUIAR PESSOA", "ROBERTA DE JESUS FERREIRA SANTOS", "ROSA MARIA PAULINO DE SOUSA", "SALETE RODRIGUES CRUZ", "TICIANY MARIA ALVES PEREIRA", "VALDERINA FARRAPO COSTA", "MARIA ONETE RIBEIRO CALDERARO DA SILVA", "MARIA AURILEIDE DOS SANTOS", "TIAGO DE LIMA SILVA", "ANA JOELHA CARNEIRO", "ANA PAULA CRUZ DO NASCIMENTO", "FERNANDA RODRIGUES DA SILVA", "FRANCISCO EDSON DUARTE DE SOUSA", "JOSE ALVES CARNEIRO", "RAIMUNDA ELAYNE RODRIGUES SOARES", "RIRONE SOUSA LOPES", "SANDRA MARIA DA CONCEICAO DA SILVA", "FRANCISCA MARQUES DE SOUSA", "MARIANA ALBANHA DOS SANTOS BRATZ", "FRANCISCA APARECIDA BARBOSA", "FRANCISCO HELOISO FERREIRA DE BRITO", "GESSICA FERNANDES SILVA", "JOELMA ALVES RODRIGUES", "MARIA GORETE VASCONCELOS", "REBECA NIVEA ARAUJO", "SIMONE SILVA ALVES", "TEREZA MARIA MESQUITA SOUZA", "CARMEMSILVA BEZERRA GOMES", "FRANCISCA VERONICA RODRIGUES DUARTE", "JOSE DILSON GOMES", "RAFAELA MONTE DA SILVA", "GLEIDSON MENDES MELO", "ISAQUE ALMEIDA BEZERRA", "FATIMA GEANE RIPARDO BATISTA", "FRANCISCO JOSE BERNARDINO DO NASCIMENTO", "JOELZA RODRIGUES FERREIRA", "JOSE TAVARES DE OLIVEIRA FILHO", "MARIA RENATA BORGES", "ANA FLAVIA SOUSA DE ARAUJO", "CLEMILDA DE LIMA ALBUQUERQUE", "FRANCISCO GALVAN SIMAO DA SILVA", "VANDERSON RODRIGUES NASCIMENTO", "ALEXANDRE DO NASCIMENTO ARAUJO", "DAIANNY RODRIGUES LOPES", "EVANDRO BRITO DE ANDRADE", "FRANCISCA ANA DOS SANTOS SOUSA", "FRANCISCO ARTUR COSTA BASTOS", "GABRIEL MOTA FERREIRA", "GLAIZA CASSIMIRO PAIVA", "LUIS FELIPE DE SOUSA BRANDAO", "MARCELA MELO RODRIGUES", "MARIA GLEICIA PAIVA LUCAS", "MARIA NAYARA BASTOS DE FREITAS SOUSA", "MICHELLE MARTINS VIANA", "AUFRAN JUNIOR ALBUQUERQUE TELES", "DANIEL ROSENDO DE OLIVEIRA", "FRANCISCO ANTUNES RODRIGUES DOS SANTOS", "FRANCISCO REGIS CORDEIRO DA SILVA", "JOSE GOMES BRAGA", "JOSE WELLINGTON RODRIGUES DE LIMA", "MARCIANO VASCONCELOS FERREIRA", "MARCIA PONTES DIAS ALVES", "MARIA CRISTIANE GOMES", "PAULO CEZAR VASCONCELOS", "PAULO RICARDO MESQUITA MOREIRA", "RAIMUNDO CLEHILTON MARQUES SOUSA", "REGIANE RIPARDO MAIA", "BENEDITA BEZERRA FROTA", "CLECIO EMANUEL MARTINS FREITAS", "EDMAR MIRANDA AVILA JUNIOR", "EMANUELA TORRES VASCONCELOS", "FRANCISCA LUZINETE DE ALBUQUERQUE PEREIRA", "FRANCISCO BRITO AZEVEDO", "JAQUELINE DE SOUSA FERREIRA", "MARIA ADRIANA DOS SANTOS CARNEIRO", "FRANCISCO IVAN FERREIRA DE SOUSA", "IVANESSA COELHO RODRIGUES", "JAQUELINE COSTA SOARES DA ROCHA", "JOSE ADALBERTO FERREIRA ARAUJO", "LEANDRO PORTELA DE LIMA", "MAGNUN PORTELA PEREIRA", "MARIA DAS GRACAS LIMA", "VALDERLANE GOMES DE ALBUQUERQUE VAZ CORDEIRO", "ALUANA PONTE MENEZES", "ATILA GOMES FERREIRA DA SILVA", "FRANCISCO LEANDRO LOURENCO DO NASCIMENTO", "MARIA ABIGAIL GONCALVES", "SANDRA REGIA DA SILVA", "SONIA MACHADO DA PONTE", "TADEU ALVES MEDEIROS", "FRANCILENE GONCALVES ELIOTERIO", "THAIS LOIOLA MAGALHAES", "ADRIANA MADEIRA DE LIMA", "ANTONIA MARIA FELIX", "CLARICE LOPES DE SOUSA", "FRANSQUINHA VASCONCELOS DOS SANTOS", "MARIA IRISMAR SOUSA", "FRANCISCA DANIELE VIANA PONTE MESQUITA", "AGUIDA MARIA ARAUJO", "ASENATE MOURA ALMEIDA", "CLEIDINI PAIVA LOPES", "FRANCISCO ANTONIO TEOFILO ANDRE", "FRANCISCO ARISTIDES PINTO MENDES", "ISAQUE ALMEIDA BEZERRA", "JOSE AUDANIO AVILA PINTO", "MARIA AURECILIA AVILA PINTO", "MARIA LUCIENE SIQUEIRA", "SILVIA HELENA MENDES HONORIO MESQUITA", "VALDIANA LOPES DE AVILA", "VANUZA AVILA ROCHA", "FRANCISCO AIRTON MENDES", "ROBERVANDA ALVES PINTO", "JENIFFER PEREIRA ROCHA VALE", "ANA PATRICIA MONCAO FIGUEREDO", "ANTONIA RODRIGUES MADEIRO", "CRISTIANO CAIXEIRO NASCIMENTO", "ERINE MAGALHAES RODRIGUES", "FRANCISCO MOZART ALVES CARNEIRO", "HELIDA RODRIGUES DA SILVA", "KELVIA MARIA DIAS JANUARIO", "LINNEKER FREIRE FROTA", "MACARIO CAETANO DE MENDONCA FILHO", "MARIA DA CONCEICAO LAUREANO OLIVEIRA", "RAFAEL DANTAS DA SILVA", "VALERIA RIBEIRO MARQUES FERNANDES", "REJANE MARIA DA PONTE VASCONCELOS", "DANIELA MARIA DE SOUSA AGUIAR", "OSMILDO PORTELA PONTES", "THAIS LACERDA DE AZEVEDO", "TERESINHA DE ARAGAO GOMES", "ANDRESSA KELLE DE SOUSA", "ANGELA CARLA SILVA DA COSTA", "ANTONIA LUCEMA MENDES PAIVA", "CINTHIA PAIXAO DOS SANTOS", "CLAUDIANA BRITO DE PAIVA", "CONCEICAO DE MARIA CRUZ RODRIGUES", "ELIDA JANE PORFIRIO FARIAS", "ELOA SALGADO DE CARVALHO BARBOSA", "FRANCISCA JOELIA NEVES", "IRENE MATOS DE SOUSA", "MARIA AURENI DE PAULO ANDRADE", "MARIA AURILEIDE DOS SANTOS", "MARIA AURIMAR GUIMARAES XIMENES", "MARIA DO SOCORRO SALES RIBEIRO GALVAO", "SHIRLEY SANDRA DE SOUSA ARAUJO", "SILVANA MARIA DA SILVA CHAGAS", "SOLANGE MARIA FREIRE DA SILVA RODRIGUES", "TERESINHA DE JESUS PARENTE LINHARES", "IVAN LENNON DA COSTA NOGUEIRA", "MARIA ONETE RIBEIRO CALDERARO DA SILVA", "AURINELIA DE SOUSA SILVA", "REJANE MARIA SILVA LIMA", "IRISBEL LIMA DE ALCANTARA", "ANTONIO MARCOS DO NASCIMENTO", "DIANA MARA DE SOUZA MATOS", "MARIA AUXILIADORA XIMENES DE SOUSA", "MARIA JACIARA RODRIGUES MELO FEIJAO", "MOUSIELY SAMYA SOARES MOREIRA", "RENI MARIA SILVA", "CELINA EDUARDO SOUZA", "GLEICE KELLY FROTA DE CASTRO", "MARIA DA CONCEICAO GOMES ALVES", "MARIA DA CONCEICAO ALCANTARA", "MARIA ELAINE ARAUJO DAMASCENO", "MARIA VANI GOMES", "MARIANA ALBANHA DOS SANTOS BRATZ", "VALNEIDE DE ARAUJO FELIX", "SANDRINE MENEZES PONTE", "ADELAIDE ALINE PORTELA ALMEIDA", "ANA CLAUDIA GRACIANO DE HOLANDA", "ANA PAULA RODRIGUES DA SILVA", "ANTONIA EDILMA MOREIRA ALBUQUERQUE", "CAMILA ALVES DA SILVA", "CLAUDIA VERAS DOS SANTOS", "EDILENE VIEIRA ALVES", "FRANCISCA ERIKA DA SILVA SOUSA", "FRANCISCO NEWTON DO NASCIMENTO SANTOS", "GLAUCIANE FEIJAO DO NASCIMENTO", "KERGIANE MENESES PRADO NEPOMUCENO", "LUZIA DO NASCIMENTO GOMES", "MAGALI SANTOS MOTA", "MARIA ALZENIRA MARQUES BARROSO", "MARIA AUXILIADORA CAVALCANTE FERREIRA", "MARIA DO SOCORRO SOUSA SILVA", "MARIA LUCIA DA COSTA", "PATRICIA ALBUQUERQUE SOUSA", "ROSA MARIA FERREIRA DO NASCIMENTO", "THAYNAH VASCONCELOS ARAGAO", "VERA LUCIA DE SOUSA FERNANDES", "CARLA THIARA DE ARAUJO SOUSA", "GRACE DONATO DE MOURA", "JULIANA BARBOSA SILVA", "ANA BEATRIZ RODRIGUES PINTO", "ANA CLEBIA ARAUJO BRANDAO", "ANTONIA APARECIDA FERREIRA RODRIGUES", "ANTONIO DUARTE RODRIGUES", "ARNOBIO BARBOZA AVILA", "DANIELE MESQUITA GERONIMO", "GLEIDSON MENDES MELO", "JORGE HALANDERSON AVILA MAGALHAES", "LUIZA ROZIANE ALVES BRAGA", "MAGNA BRAGA OLIVEIRA MAGALHAES", "RAIMUNDA NONATA SARAIVA PINTO", "RAIMUNDO NONATO DA SILVA COSTA", "MANUEL FERNANDES DE ARAUJO NETO", "CAMILO SOUSA CAVALCANTE LETRAS", "ANTONIO WESCLEY BARROS DUARTE", "BRUNO DA COSTA OLIVEIRA", "EDILAINY MARIA DOS SANTOS FARIAS", "FRANCISCA GUILHERMINA BRASILEIRO MAGALHAES", "PEDRO ARILSON PINHEIRO RODRIGUES", "SELMA MARIA VIANA", "VERONICA DE BRITO LIMA", "MARIA ALZENIRA MARQUES BARROSO", "NATANAEL ROMAO GADELHA", "ALEXANDRINA VASCONCELOS GOMES", "FRANCISCA SHIRLEY ARAUJO FERREIRA", "FRANCISCO SILVIO PEREIRA DUARTE", "JOSE HERMENEGILDO MESQUITA VIANA", "MARIA AUGUSTA DA SILVA GOMES", "MARIA DA CONCEICAO GOMES CARNEIRO", "MARIA ELENICE RODRIGUES FEIJAO", "MARIA OTILIA MONTEIRO GOMES", "MARIA VALDEVANDA SANTANA GOMES", "MARINA DA SILVA DE CARVALHO", "RUTHIELLE MARTINS PRADO", "AMANDA DA COSTA SOUSA AGUIAR", "FRANCISCO GEOVANE DA SILVA ARAUJO", "ANTONIA DAMASCENO ALVES PONTES", "DANIELE DE BRITO RIBEIRO", "GEANE KELLY PEREIRA CORDEIRO", "JOAO PAULO DA SILVA", "LEILIANE MACHADO PORTELA", "MARIA DO REMEDIO DE SOUSA ALVES", "MARIA IARA BRITO E SILVA", "VALERIA LOPES RODRIGUES", "FRANCISCO DAS CHAGAS FERREIRA CAVALCANTE", "ANA CLAUDIA MOURA ALMEIDA", "FRANCISCA WAGNA BRAGA VASCONCELOS", "FRANCISCO AIRTON MENDES", "GESSICA MAGALHAES RIBEIRO", "JOSE WILSON RODRIGUES PINTO", "MILENA AVILA GONCALVES", "ROBERVANDA ALVES PINTO", "TELMA MENDES PINTO", "URCULA MARIA ALMEIDA MENDES", "THAISA FERREIRA MUNIZ", "KELLY LIMA BARROSO", "KEILA PEREIRA DE LIMA", "MARIA DA PIEDADE DE ALBUQUERQUE", "FERNANDA KARLA FELISMINO PIMENTEL", "ANTONIO FERNANDES TOMAZ FILHO", "CLECIVANE OLIVEIRA ALBUQUERQUE", "FRANCISCA JULIA AVELINO MARREIRO", "FRANCISCA RODRIGUES SAMPAIO", "FRANCISCA SHIRLEANE FERREIRA ARAGAO", "IVAN LENNON DA COSTA NOGUEIRA", "JANIA MARIA RODRIGUES DOS SANTOS", "RAIMUNDA NONATA BATISTA DE OLIVEIRA", "TIANA MARA DOURADO DE SOUSA", "VERONICA MARTINS MORAIS", "SEBASTIAO DOMINGOS DE SOUZA", "APOLONIA MACHADO MESQUITA", "APOLONIA MACHADO DA SILVA", "CLAYTIANE RIBEIRO DA SILVA", "GREICIANE DE SOUSA", "JOSIANE LIMA DE ARRUDA", "AGUIDA PAULA DUARTE BRITO", "AYLA MARIA DE ANDRADE LIMA", "GLEIVIANE VITORINO FERREIRA", "MARIA TARCIANE MACHADO DE ALBUQUERQUE", "RAFAEL MANOEL DA PONTE VENUTO", "RAIMUNDO NONATO ALEXANDRE FILHO", "MARIA DE FATIMA GOMES APOLIANO", "EDINEUDA BEZERRA", "FRANCISCA DAS CHAGAS DE OLIVEIRA MESQUITA", "JULIANA ALVES DE SOUSA", "SOLANGE MESQUITA BALBINO", "APOLONIA MACHADO MESQUITA", "ANA CARLA DE MESQUITA", "ANDREIA GOMES SANTANA", "CLECIA TEIXEIRA DE PAIVA", "EDNA MARIA DE SOUSA", "FABIANA SOUSA FERNANDES", "FRANCISCA DAS CHAGAS LINHARES RIBEIRO DE MENEZES", "FRANCISCA FRANCILENE DE OLIVEIRA CARLOS", "FRANCISCA LUCIA MARQUES DE ARAGAO", "FRANCISCA ROGELMA ALVES", "JOREOLANA BRITO DA SILVA", "MARIA DIVA NEVES MENDES CARNEIRO", "MARIA DO SOCORRO MESQUITA SOUSA", "MARIA DO SOCORRO PARENTE VASCONCELOS", "MARIA SUELY SALES FERREIRA", "NEOMESIA MONTEIRO LOPES", "REGINA TELMA DIAS FERREIRA", "ROSIMEIRE DE LIMA MELO", "MARIA DO SOCORRO SOUSA SILVA", "GAUGANHA MARIA SOUSA VASCONCELOS", "ADINELIA DE FATIMA SILVA CANTANHEDE", "ADRIANA PAULA CARVALHO", "AMANDA BEZERRA LOPES", "ANA CARLA CASTRO SOUSA", "ANA LUCIA DE JESUS", "ANA PAULA FROTA DE SOUZA", "ANA SERGIA TREVIA MOURA", "CRISLEYANE DA SILVA TOMAIS", "FRANCISCO NEUTON CORDEIRO DUARTE", "JACIRA RIPARDO XAVIER", "JOCILANE DE MESQUITA ALBUQUERQUE", "KLEBER VIEIRA MANCO", "LUCIANA LIMA ARAGAO", "LUCICLEIDE ROMAO SILVA", "NAGILA MAGALHAES LUCAS", "RAIMUNDO NONATO COUTINHO", "SAMYLA NASCIMENTO DE SOUSA", "MARCOS ANTONIO DE OLIVEIRA FILHO", "SINARA NASCIMENTO DO CARMO", "ANTONIA ALINE GAMA DE OLIVEIRA", "KLEITON ARRUDA SALES", "ADRIANA BARBOSA DO NASCIMENTO", "CANDIDA ANDREA DE MESQUITA MENDES", "DANIELLE MARIA MENEZES DE SOUSA", "ELIANE MONTE BARBOZA PAIVA", "FRANCISCO DO CARMO SILVA", "FRANCISCO WASHINGTON RODRIGUES DE FARIAS", "GLAUCIANA FERREIRA CARNEIRO LOPES", "HELENILDA ARAUJO DO MONTE", "JANDERLY DO MONTE DE ARAUJO", "JOSE ARISTEU DO NASCIMENTO", "MARIA DILMA MONTE", "MARIA LUCIANA PONTE PARENTE", "RAIMUNDA CELIA LINHARES PONTE", "RAPHAEL GOMES VALE", "ROMARIO FREIRE ALCANTARA", "SAMARA DA SILVA", "SILVELANE MARIA AZEVEDO LIMA", "TATIANA SOUZA CAJADO MOURA", "ZELIA CAETANO DOS SANTOS SILVA", "ANA CRISTINA RIBEIRO MENEZES", "ANA JAMILLE AGUIAR PARENTE", "APARECIDA CASSIMIRO DE LIMA", "EMANUELLE COSTA RIPARDO", "ENILBA PARENTE DE MENEZES", "FRANCILENE GONCALVES ELIOTERIO", "FRANCISCA LUSIELMA LINHARES", "FRANCISCO EDMILSON SILVA", "MARIA DE FATIMA DE OLIVEIRA PONTE", "MARIA DE JESUS AGUIAR", "MARIA DO SOCORRO ANDRADE LIMA", "MARIA ELIANE ALVES PEREIRA", "SANDRA REGIA DE SOUSA", "ANTONIA PATRICIA LIMA", "KELLY ABREU SILVA", "ANA PATRICIA CARNEIRO DE LIMA", "EVILANE DA SILVA LINO", "FABIANE VASCONCELOS MARQUES", "FRANCISCA EDILENE MATIAS DA SILVA", "HERTAN BRUNO NASCIMENTO DE ARAUJO", "MANUEL ROMERO FURTADO DE SOUSA", "SILVIA HELENA AGUIAR DA SILVA RIBEIRO", "DAIANA MARIA FELIX CAVALCANTE", "ANGELA MARIA CARNEIRO ARAUJO", "ANNE GRAZIELLE SOUZA OLIVEIRA LIESEMBERG", "ANTONIA EXPEDIANA DE ARAUJO ABREU", "ANTONIA FLAVIA SILVA DE AGUIAR", "ANTONIA GRIJAELLA MESQUITA REIS", "DAYANA LIMA LEITAO DA COSTA", "ELIETE DE SOUSA VASCONCELOS", "FABIULA FEITOSA RODRIGUES", "FRANCISCA EMANUELA RIBEIRO DE SOUSA", "FRANCISCO AUGUSTO RODRIGUES FERREIRA", "JULYA CARNEIRO MESQUITA DE LIMA", "LUCIANA DA SOLEDADE DE ARAUJO CARNEIRO", "LUCIA MARIA SOUSA SILVA", "MARIA GLAUCIVANE SAMPAIO PORTELA", "MARIA RODRIGUES DOS SANTOS", "RENATA MARIA DE SOUSA", "SANDRA MARIA DE ALMEIDA OLIVEIRA", "SUELY TEODORO DE CASTRO ALMEIDA", "WILDIANE GONCALVES DO NASCIMENTO", "EDUARDO RODRIGUES DE SOUSA", "FRANCISCO FREIRE ALCANTARA FILHO", "ANTONIA ROSEMEIRE MORAES RIBEIRO PORTELA", "ELENILDA DA SILVA DO NASCIMENTO", "ALCINEIDE PINTO DE SOUZA", "ANGELICA MARIA DE FARIAS", "CELIA MARIA LIMA VASCONCELOS", "EDUARDO RODRIGUES DE SOUSA", "EUZENY MAMEDE AMORIM", "FRANCISCA MARCIA CEDRO DE SOUSA", "FRANCISCO REGINALDO ARAUJO DE SOUSA", "GENILDA RIPARDO DA PONTE", "GENOVINA MARIA PEREIRA ANDRADE", "JOSELANDIA DE SOUSA OLIVEIRA", "KATIA CRISTINA GOMES LINO", "LUZIA TRINDADE FRANCA", "LUZINETE CHAGAS NASCIMENTO", "MARIA DE FATIMA FERNANDES DE AGUIAR PARENTE", "MARIA DO CARMO DE PAULO DO NASCIMENTO", "MARIA GORETE FAUSTINO", "MARIA JARINA BEZERRA ARAGAO", "SARA ROCHA SILVA", "SILVANA SILVA DE SOUZA", "TERESINHA LIBERATO VIANA", "JOSIEL MOTA PEREIRA", "ANTONIA ROSEMEIRE MORAES RIBEIRO PORTELA", "GEORGIA DA SILVA CHAGAS", "AMANDA IRIS ARAGAO SANTOS", "ANTONIA ALCINETE MARCIEL VICENTE", "ANTONIO RAMON FIRMO DA COSTA", "CAETANO DA PONTE MACHADO", "CLEIDE DO NASCIMENTO CARLOS", "FERNANDO LOPES FERREIRA", "FRANCISCA CARNEIRO DOS SANTOS", "JUSCIELTON MARQUES MONTE", "NATANAEL ROMAO GADELHA", "SILVANA MARIA DE SOUSA", "JOSE EDUARDO DE MESQUITA", "NILTON DO VALE CAVALCANTE", "FRANCISCA MARIA VASCONCELOS QUARIGUASI AUZIER", "VALESKA SIRIDO LIMA", "MARIA AUXILIADORA CARNEIRO AUZIER", "CONCEICAO DE MARIA COSTA DE PAULA CLEMENTE", "CRISTIANE MARIA VASCONCELOS LINHARES", "ELBA MARIA AGUSTINHO DE SOUZA", "FRANCISCA MARIANA DA SILVA NUNES", "FRANCISCO KLEBER RODRIGUES ALVES", "GILBERTO MACIEL PAIVA JUNIOR", "IVANIA MACHADO XIMENES", "JOAO FERREIRA DOMINGOS FILHO", "JOSIEL MOTA PEREIRA", "KATIDIANE VASCONCELOS BEZERRA ROCHA", "MARCOS ANTONIO DE OLIVEIRA FILHO", "MARIA DAIANE DUARTE DE VASCONCELOS", "MIKAELE CORREIA DA SILVA MOURA", "NILTON DO VALE CAVALCANTE", "RENATO ANTONIO COSTA", "ROSA MARLENE DA SILVA SOUSA", "MOUSIELY SAMYA SOARES MOREIRA", "LIDUINA SILVINO DE SALES", "MARIA ELIZETE TEIXEIRA GONCALVES", "NEYLA CRISTINA SILVA DA COSTA", "ROSILANINA MARIA DE VASCONCELOS", "MARIA IRISMAR SOUSA", "ALEXSANDRA MARIA COELHO SALES", "ANA CARMEM PAULA PESSOA DIAS ANDRADE", "ANA LUCIA MESQUITA FROTA", "ANA MARCIA DE OLIVEIRA CARVALHO ARAGAO", "FABIOLA SILVA CARNEIRO", "IRACEMA AGUIAR DA CRUZ", "MARIA DE FATIMA LOPES VASCONCELOS", "NOEME SOUZA IBIAPINA", "ROSANGELA MARIA DE SOUZA", "SAMARA RIBEIRO DE SOUSA", "SILVANA BRAGA CARNEIRO", "FRANCISCA MARQUES DE SOUSA", "ANA CARLA ARAUJO SOUSA VIDAL", "ANA CLEVIA ROMAO SILVA", "ENAILE MARIA MARTINS MORORO", "ISIANE ALVES DE OLIVEIRA", "JOSEFA COSTA SILVA", "KELLIANE FERREIRA LIMA", "ROSANGELA MARIA MENDES DA SILVA", "ROSA MARIA SOUSA MENDES", "TAMIRES KELCIA DO NASCIMENTO DE OLIVEIRA", "ANTONIO ACÁCIO AGUIAR GOMES", "ANNE VALERIA SERAFIM", "ANTONIA NOELIA LOPES ROCHA", "DANIELLE LUIZE SANTOS DE OLIVEIRA", "EMANUELA MATOS FERREIRA", "FLAVIO LOIOLA FROTA", "FRANCISCO ALLAN SOUSA SALES", "FRANCISCO CESAR RODRIGUES", "KARLYANE PIMENTA DE CARVALHO COSTA", "LUCE PATRICIA VASCONCELOS DE ALBUQUERQUE", "MAGDALA HEVELLIN SOUSA DUARTE", "MARIA IVONETE BRAZ SOUZA", "NATALIA MARIA DE CARVALHO", "RARISSON ALEXANDRE FELIX", "REJANE MARIA DA PONTE VASCONCELOS", "SUIANE VIRGINIA PEREIRA LOIOLA", "TAINA EMANUELLY BARBALHO DA SILVA", "PAULA MARIA SILVA DO NASCIMENTO", "ANTONIA BRUNA BASTOS DO NASCIMENTO", "FRANCISCA MARIA BEZERRA ALVES", "FRANCISCO WELLINGTON ARRUDA LINHARES", "KELLY ABREU SILVA", "MARIA DO AMPARO LINHARES", "RAQUEL AUGUSTA DE MOURA", "EDILENE VIEIRA ALVES", "RAIMUNDO NONATO ALEXANDRE FILHO", "ANTONIO CARLOS CARREIRO CHAVES", "FRANCISCO DANIEL ALVES CAMPOS", "GRACE DONATO DE MOURA", "ISABELE MUNIZ FERREIRA", "JOANA KARLA CARDOSO CRUZ DE ANDRADE", "JORGIANE DE SOUZA GAMELEIRA", "JOSE EDUARDO DE MESQUITA", "KAROLAYNE SUELLEN CAVALCANTE SILVA", "SANDRA MARIA DOS REIS FEIJAO", "SEBASTIAO SOARES DE SOUSA JUNIOR", "MARIA CRISTIANE GOMES", "NAYARA SILVA DE OLIVEIRA", "RAIMUNDO CLEHILTON MARQUES SOUSA", "CIDALIA BEZERRA DOS SANTOS NETO", "MANUELA CARLA DO NASCIMENTO SOUZA DOS SANTOS", "MARIA JEÍZA PEREIRA DE MATOS", "MARIA IVANI SOUZA", "MARIA LIGIA LOPES LAURINDO", "ALEXANDRA MARIA SILVA DE CASTRO", "ANA ALICE FERREIRA DE PAULA", "ANA KARLA VASCONCELOS", "ANA MIKAELLY MADEIRA ALBUQUERQUE", "CARLA THIARA DE ARAUJO SOUSA", "FRANCINILDA RODRIGUES ANDRADE VASCONCELOS", "FRANCISCA PINTO TAVARES ARAGAO", "FRANCISCO JANIO RODRIGUES", "JOAO BATISTA LIMA ARAGAO", "JOSE RIBAMAR GOMES", "MARA REGIA SILVA DA COSTA", "MARCIA JACKELINE DE SOUSA OLIVEIRA", "MARCIA MARIA GONCALVES DE MESQUITA", "MARIA CELMER RONCY", "MARIA DA CONCEICAO GOMES MENDES", "MARIA DO CARMO SILVA DE MESQUITA", "MARIA ELIENE PORTO RODRIGUES", "MARIA ESTELA AMBROSIO FELIX", "MARIA LIDIANE DE SOUSA MELO", "MARIA OZENICE OLIVEIRA", "MARIA SIMONE DE FARIAS HILARIO", "NAIZA MARIA SILVA OLIVEIRA", "PATRICIA NASCIMENTO AGUIAR", "ROSANGELA SILVA DA COSTA", "ROSA MARIA TORRES SEGUNDO", "ADRIANA DE OLIVEIRA", "ANA TAFNES DE SOUSA RODRIGUES", "ANTONIO MARIO ALVES DO NASCIMENTO", "DOUGLAS ABREU BRAGA DE SOUZA", "ERTON FREIRE LAUREANO", "FRANCISCA ISAQUIELY XIMENES ARAUJO", "JOSIER RIPARDO NASCIMENTO", "JULIANA BARBOSA SILVA", "LILIANE MARIA MACEDO FERREIRA", "MARCIA SOARES FERNANDES", "MARIA JOSIANE MOREIRA DE SAMPAIO", "NAYARA SILVA DE OLIVEIRA", "RAIMUNDO NONATO MONTEIRO", "ROMERIO FREIRE ALCANTARA", "ANTONIA DE FATIMA CAMPOS", "ANTONIA ELI FERREIRA LIMA MOURA", "EMANUEL ALISSON DAMASCENO", "MARCELA PORTELA PONTES CORREIA", "MARIANA CRISTINA TELES ARAUJO", "MARIA JANIA DE SOUSA", "MARIA MARCIA LIMA", "VANESSA LIMA NERY OLIVEIRA"]


export { pessoasEmail, pessoasComparar};